---
settings:
  name: XCP
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: Home
      url: /home.html
    - title: Release Notes
      url: /releasenotes.html
    - title: Get started with XCP
      type: solutions
      entries:
        - title: Learn about XCP  
          url: /index.html
        - title: XCP NFS add-on features
          url: /xcp-nfs-add-ons.html
        - title: Unsupported features
          url: /xcp-unsupported-features.html
        - title: Supported configurations
          url: /xcp-supported-configurations.html
        - title: Ports used by XCP
          url: /xcp-ports-used.html
    - title: Install XCP
      entries:
        - title: Prepare for XCP installation   
          url: /xcp-install-xcp.html
        - title: Prepare Linux for XCP NFS
          url: /xcp-prepare-linux-for-xcp-nfs.html
        - title: Prepare Windows for XCP SMB
          url: /xcp-prepare-windows-for-xcp-smb.html
        - title: Prepare File Analytics
          url: /xcp-prepare-file-analytics.html
        - title: Install XCP NFS
          url: /xcp-install-xcp-nfs.html
        - title: Install XCP SMB
          url: /xcp-install-xcp-smb.html
        - title: Install File Analytics for NFS
          url: /xcp-install-file-analytics-for-nfs.html
        - title: Install File Analytics for SMB
          url: /xcp-install-file-analytics-for-smb.html
    - title: Configure XCP
      entries:
        - title: Configure the INI file for XCP NFS
          url: /xcp-configure-the-ini-file-for-xcp-nfs.html
        - title: Performance tuning
          url: /xcp-performance-tuning.html
        - title: Environment variable
          url: /xcp-environment-variable.html
        - title: Configure the POSIX connector
          url: /xcp-configure-posix-connector-nfs.html
        - title: Configure the HDFS connector
          url: /xcp-configure-hdfs-connector-nfs.html
        - title: Configure multinode scale-out
          url: /xcp-configure-multinode-scaleout-nfs.html
        - title: Configure the S3 connector
          url: /xcp-configure-s3-connector-nfs.html
    - title: Plan data migration
      url: /xcp-plan-data-migration.html
      entries:
        - title: Plan NFS data migration
          url: /xcp-plan-nfs-data-migration.html
        - title: Plan SMB data migration
          url: /xcp-plan-smb-data-migration.html
        - title: Plan HDFS data migration
          url: /xcp-plan-hdfs-data-migration.html
        - title: Plan using File Analytics
          url: /xcp-using-file-analytics.html
          entries:
            - title: Access File Analytics
              url: /xcp-access-file-analytics.html
            - title: Add file servers
              url: /xcp-add-file-servers.html
            - title: Run a scan
              url: /xcp-run-a-scan.html
        - title: Filters
          url: /xcp-filters.html
        - title: Logging for NFS and SMB (optional)
          url: /xcp-logging-for-nfs-and-smb.html
    - title: Migrate data
      entries:
        - title: Migrate NFS data
          url: /xcp-migrate-data.html
        - title: Migrate SMB data
          url: /xcp-migrate-smb-data.html
        - title: Migrate HDFS data
          url: /xcp-migrate-hdfs-data.html
        - title: Run multiple XCP jobs on the same host 
          url: /xcp-run-multiple-jobs-on-same-host.html
        - title: Additional NFS features
          url: /xcp-migrate-nfs-additional-features.html
    - title:  Troubleshoot
      entries: 
        - title: Troubleshoot XCP NFS errors
          url: /xcp-troubleshoot-xcp-nfs.html
        - title: Troubleshoot XCP SMB Errors
          url: /xcp-troubleshoot-xcp-smb-errors.html
        - title: Troubleshoot XCP File Analytics errors
          url: /xcp-troubleshoot-xcp-file-analytics-errors.html
    - title: Get more information
      url: /get-more-information.html

