---
sidebar: sidebar
permalink: xcp-configure-s3-connector-nfs.html
keywords: xcp, configure, nfs, S3, connector
summary: The S3 connector gives XCP the capability to migrate data from an NFS or HDFS file system to the S3 object storage
---

= Configure the S3 connector

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Beginning with XCP 1.9.2, the Simple Storage Service (S3) connector enhances the scope of XCP data migration by enabling data migration from NFS or Hadoop Distributed File System (HDFS) file systems to  S3 object storage.

.Supported migration use cases
The following migration use cases are supported for the S3 connectors:

* Migration from HDFS or NFS to NetApp StorageGRID
* Migration from HDFS or NFS to Amazon S3
* Migration from HDFS or NFS to NetApp ONTAP S3 

NOTE: Currently MapR is only qualified and supported for HDFS.

.Supported features
Support for the `scan`, `copy`, `verify`, `resume` and `delete` commands is available for the S3 connectors.

.Unsupported Features
Support for the `sync` command is not available for the S3 connectors.

.Path Syntax
The path syntax for the S3 connector is `s3://<bucket in S3>`.

* You can provide a specific S3 profile for the XCP commands using the `-s3.profile` option.
* You can use the `s3.endpoint` option to modify the endpoint value to communicate with S3

NOTE: Endpoint usage is mandatory for StorageGRID and ONTAP S3.

== Set up an S3 connector

.Steps

. To run the XCP command with the S3 connector, create a bucket in S3 by following the online documentation for the respective platforms:

* link:https://docs.netapp.com/us-en/ontap/object-storage-management/index.html[ONTAP S3 object storage management^]
* link:https://docs.netapp.com/us-en/storagegrid-116/tenant/index.html[Use a tenant account: Overview^]
+
NOTE: Before continuing, you must have the URL for the `access key`, `secret key`, `ssl-certifcate`, and `endpoint` parameters as XCP identifies and connects to the S3 bucket using these parameters before initiating an operation.

. Install the Amazon Web Services (AWS) CLI packages and run the AWS CLI commands to configure the keys and Secure Sockets Layer (SSL) certificates for S3 accounts:

* See link:https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html[Installing or updating the latest version of the AWS CLI^] to install the AWS packages.
* See the link:https://docs.aws.amazon.com/cli/latest/reference/configure/set.html[AWS CLI Command Reference^] for more information.

. Use the `aws configure` command to configure your credentials file. By default, the file's location is `/root/.aws/credentials`. The credentials file should specify the access key and secret access key. In the following example, the key and secret key for the account are specified in the default profile:
+
----
[default]
aws_access_key_id = YOUR_ACCESS_KEY
aws_secret_access_key = YOUR_SECRET_KEY
----

. Use the `aws configure set` command to specify a certificate authority (CA) certificate bundle, which is a file with the `.pem` extension that is used when verifying SSL certificates. By default, the file's location is `/root/.aws/config`. 
+
----
[default]
ca_bundle = /u/app/s3/ca-certs/cabundle-s3.pem
----

. Before running the XCP command, ensure that the AWS CLI commands can access the S3 buckets from the Linux client with the required setup configuration:
`aws s3 ls --endpoint-url <ENDPOINT> s3://bucket-name/`
+
`aws s3 ls --profile <profile> --endpoint-url <ENDPOINT> s3://bucket-name`
+
----
[root@scs000132093-1 linux]# aws s3 ls --profile xx --endpoint https://rtplabsg02.eng.netapp.com:443 s3://xxxx-bucket
                           PRE 1G/
                           PRE aws_files/
                           PRE copied_folders/
                           PRE d1/
                           PRE d2/
                           PRE giant_size_dirs/
                           PRE medium_size_dirs/
                           PRE small_size_dirs/
[root@scs000132093-1 l
----

// 2023-06-09, XCP 1.9.2
