---
sidebar: sidebar
permalink: xcp-install-file-analytics-for-nfs.html
keywords: netapp, xcp, install, installing, file, analytics, nfs, upgrade, upgrading
summary: Install or upgrade File Analytics for NFS
---

= Install File Analytics for NFS
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Install or upgrade File Analytics for NFS.

.About this task
For system requirements for NFS, see link:xcp-install-xcp-nfs.html[Install XCP NFS].

The `configure.sh` script installs XCP File Analytics on a Red Hat Enterprise Linux (RHEL) host machine. As part of the installation, the script installs Postgres Database, Apache HTTPD server, and other required packages on the host Linux machine. For information on specific supported RHEL versions, refer to the link:https://mysupport.netapp.com/matrix/[IMT^]. You can change or update to a more recent version as needed and to adhere to security guidelines. To learn more about the `configure.sh` script, run `./configure.sh -h` on the command line.

.Before you begin

* If any XCP operations are running, NetApp recommends that you complete the operations before you start configuration.
* Your Linux machine must be connected to the Yum repository server or the internet.
* If a firewall is configured on the Linux machine, you must change the firewall settings to enable port 5030 used by the XCP service. 

.Steps

. Install or upgrade File Analytics for NFS.
+
[role="tabbed-block"]
====
.Install File Analytics
--
.. Navigate to the `xcp` folder and run the `./configure.sh` script.
+
If installation is successful, the following message is displayed:
+
----
You can now access XCP file analytics using (<username>:<password>)
https://<ip_address>/xcp
----
+
NOTE: You can use this username and password to log in to the File Analytics GUI.
--
.Upgrade File Analytics
--
.. Navigate to the `xcp` folder and run `./configure.sh -f`.
+
.. At the prompt, enter `y` to clean up and reconfigure the system.
+
Once approved, the script cleans up the existing configuration and reconfigures the system. 
+
If successful, the following message is displayed:
+
----
You can now access XCP file analytics using (<username>:<password>)
https://<ip_address>/xcp
----
--
====

. Launch File Analytics in a supported browser: *\https://<ip address of linux>/xcp*.
+
Refer to link:xcp-install-xcp-nfs.html[Install XCP NFS] for information on supported browsers.

// 23 Oct 2023, OTHERDOC-34
// BURT 1391465 06/29/2021
