---
sidebar: sidebar
permalink: xcp-install-file-analytics-for-smb.html
keywords: netapp, xcp, install, installing, file, analytics, smb, upgrade, upgrading
summary: Install or upgrade File Analytics for SMB
---

= Install File Analytics for SMB
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Install or upgrade File Analytics for SMB.

.About this task

For system requirements for SMB, see link:xcp-install-xcp-smb.html[Install XCP SMB].

.Before you begin

* You must configure XCP File Analytics for NFS on a Linux machine to use the XCP SMB service.
*	Make sure the XCP service is running on your Linux machine, before you begin configuring XCP File Analytics on a Windows machine.

== Fresh install of File Analytics for SMB

To perform a fresh install of File Analytics for SMB, complete the following steps.

.Steps

. Copy the `xcp.exe` file to your Windows `C:` drive, this binary is available inside `/xcp/windows` after you untar the `tgz` file.
. Download the XCP license file from the link:https://xcp.netapp.com/[XCP site^].
. Create the folder `C:\\NetApp\XCP` and copy the XCP license to this location.
. Activate the XCP license using the following command at the command prompt:  `xcp.exe activate`
. In the Windows CLI command prompt, run `xcp configure`.

. When prompted, provide the IP address of the Linux machine where the XCP File Analytics server is configured.
. Copy the `server.key` and `server.crt` files from `/opt/NetApp/xFiles/xcp/` (in the Linux box where XCP File Analytics is already configured) to `C:\NetApp\XCP`.
+
Optionally, if you have a CA certificate, place the certificate in `C:\NetApp\XCP` with the same name and extensions.

. Go to your Windows machine and run `xcp listen`, now XCP File Analytics for SMB is configured. Keep the window open to continuously run the service.
. Launch File Analytics on a supported browser: `\https://<ip address of linux>/xcp`
+
Refer to link:xcp-install-xcp-smb.html[Install XCP SMB] for information on supported browsers.
. Select `OK` when the dialog box displays.
+
NOTE: A new tab opens. Enable pop-ups on the browser if they are blocked.

. Accept the privacy policy for the URL. The following message displays: `SMB agent is ready to use. Please refresh the analytics page`
. Display the SMB agent under the Agents card by returning to the original tab hosting the XCP File Analytics GUI and refreshing the page.

== Upgrade of File Analytics for SMB

To upgrade the existing File Analytics for SMB, complete the following steps.

. Before you run File Analytics, verify that the Linux server that File Analytics is running on is also upgraded and that the service is running.
. In Windows, stop the existing XCP service by entering `CTRL-C` on the command line.
. Replace `xcp.exe` with the latest binary.
. Go to your Windows machine and run `xcp listen` to configure XCP File Analytics for SMB. Keep the window open to continuously run the service.
. Launch File Analytics on a supported browser: `\https://<ip address of linux>/xcp`
+
Refer to link:xcp-install-xcp-smb.html[Install XCP SMB] for information on supported browsers.
. Select *OK* when the dialog box displays.
+
NOTE: A new tab opens. Enable pop-ups on the browser if they are blocked.

. Accept the privacy policy for the URL. The following message displays: `SMB agent is ready to use. Please refresh the analytics page`
. Display the SMB agent under the Agents card by returning to the original tab hosting the XCP File Analytics GUI and refreshing the page.



// 23 Oct 2023, OTHERDOC-34