---
sidebar: sidebar
permalink: xcp-configure-the-ini-file-for-xcp-nfs.html
keywords: netapp, xcp, configure, configuring, how, performing, tuning, nfs,
summary: Steps to configure the INI file XCP
---

= Configure the INI file for XCP NFS
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Steps to configure the INI file for XCP.

== Configure the INI file for a root user

You can use the following procedure to configure the INI file for an XCP NFS root user.

.Steps

. Add the catalog location for the XCP server in the host configuration file by using the `vi` editor:
+
NOTE:	Catalog location should be exported before modifying the details in the `xcp.ini` XCP configuration file. Catalog location (NFSv3) should be mountable by the XCP Linux host but not necessarily be mounted.

+
----
[root@localhost /]# vi /opt/NetApp/xFiles/xcp/xcp.ini
----

.	Verify that the XCP Linux client host configuration file entries for the catalog were modified:
+
----
[root@localhost /]# cat /opt/NetApp/xFiles/xcp/xcp.ini
# Sample xcp config
[xcp]
catalog = 10.61.82.210:/vol/xcpvol/
----

== Configure the INI file for a non-root user

As a non-root user, you do not have permission to mount the NFS file system. A root user is required to first mount the catalog volume and then, as a non-root user running XCP, if you have read/write permission to the catalog volume, you can access the mounted catalog volume by using a POSIX connector. After the volume is mounted, you can add catalog the path:

----
(t/10.237.170.53_catalog_vol – This is the path where catalog volume is mounted)as follows.

[user1@scspr2474004001 xcp]$ ls -ltr
total 8
drwxrwxr-x 2 user1 user1  21 Sep 20 02:04 xcplogs
-rw-rw-r-- 1 user1 user1  71 Sep 20 02:04 xcp.ini
-rwxr-xr-x 1 user1 user1 352 Sep 20 02:10 license
[user1@scspr2474004001 xcp]$ cat /home/user1/NetApp/xFiles/xcp/xcp.ini

Sample xcp config [xcp]
catalog = file:///t/10.237.170.53_catalog_vol
----
