---
sidebar: sidebar
permalink: xcp-troubleshoot-xcp-file-analytics-errors.html
keywords: netapp, xcp, troubleshoot, troubleshooting, errors, file, anyalytics
summary: Troubleshooting XCP File Analytics errors
---

= Troubleshoot XCP File Analytics errors
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Review the solutions to troubleshoot your issue.

[cols="40,60"]
|===
|Issue |Solution

|PostgreSQL installation or service failed
a|Run configure again and select the installation option. If the previous installation was successful, you can select the repair option. If you are still getting the error, try manual steps as follows:

.	Run PostgreSQL on the Linux system
+
`sudo yum -y install postgresql-serversudo systemctl start postgresq`
+
.	Create a data directory for the PostgreSQL database:
+
`sudo mkdir /var/lib/postgres/data`
+
.	Initialize the database:
+
`sudo -i -u postgres initdb  -D '/var/lib/pgsql/data`
+
. Open the following file using an appropriate Linux file editor:
+
`/var/lib/pgsql/data/pg_hba.conf`
+
.	Remove the following entry:
+
``# host    all             all           127.0.0.1/32            trust`
+
.	Add the following entry:
`# host    all             all             0.0.0.0/0            password`
+
.	Open the file `/var/lib/pgsql/data/postgresql.conf`
+
.	Add the following entry:
+

`# listen_addresses='*'`
+
.	Start the PostgreSQL service:
+
`sudo systemctl start postgresql.service`
|HTTPD installation or service failed
a|Run configure again and select the installation option. If the previous installation was successful, you can select the repair option. If you are still getting the error, try manual steps as follows:

.	Install HTTPD on the Linux system:
+
`sudo yum -y install httpd`
+
.	Open the following configuration file to rewrite the rules:
+
`/etc/httpd/conf/httpd.conf`
+
.	Add the following entries to the file:
+
`RewriteEngine On`
`RewriteOptions Inherit`
`<Directory "/var/www/html/">`
`AllowOverride None`
`Require all granted`
`RewriteCond %{REQUEST_FILENAME} -f [OR]`
`RewriteCond %{REQUEST_FILENAME} -d`
`RewriteRule ^ - [L]`
`RewriteRule ^ xcp/index.html [L]`
`</Directory>`
+
.	Start the HTTPD services:
+
`sudo systemctl start httpd`
|SSL installation failed
a|Run configure again and select the installation option. If the previous installation was successful, you can select the repair option. If you are still getting the error, try manual steps as follows:

.	Install `mod_ssl`:
+
`yum install mod_ssl -y`
+
.	Generate the Secure Sockets Layer (SSL) certificate:
+
`yum openssl req -x509 -nodes -days 365 -newkey` `rsa:2048 -keyout /etc/ssl/private/apache`-`selfsigned.key -out /etc/ssl/certs/apache-selfsigned.crt`
+
.	Enable the HTTPS services:
+
`yum openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048`
+
.	Restart the HTTPD services:
+
`sudo systemctl restart httpd`
+
.	Copy the SSL certificate to an appropriate location:
+
`sudo cp -pr /etc/pki/tls/certs/localhost.crt /opt/NetApp/xFiles/xcp/server.crt`
`sudo cp  -pr /etc/pki/tls/private/localhost.key /opt/NetApp/xFiles/xcp/server.key`
|Not able to open login page after successful install
|Make sure your system is able to ping the Linux machine where XCP File Analytics is installed and HTTPD is running. If the services are not running, run `configure` and choose the repair option.

Make sure that you are using supported version of browser. See the IMT: https://mysupport.netapp.com/matrix/
|User login failed
a|*	Make sure that you are using a supported version of the browser. See the IMT: https://mysupport.netapp.com/matrix/
*	Check the user is “admin” and the password is correct
*	Make sure the XCP service is running by issuing “xcp service status”
*	Verify that port  5030 is open on Linux. Open the application at *https:// <linux ip> :5030/api/xcp*, and confirm that the messagereads msg: `Missing Authorization Header`
*	Check whether the `xcp.ini` file is present in the `/opt/NetApp/xFiles/xcp/` location. To reset the `xcp.ini` file, run the configuration script and select the *Repair* option. Next, select the menu option to *rebuild xcp.ini file*
|XCP GUI is not showing updated pages.
|Clear the cache and try again
|XCP service is not starting
|To run the `xcp` service, use the `sudo systectl start xcp` command. Alternatively, run the configuration script and select the *Repair* option to start the services that are stopped
|Failed to scan file share
|File share/volume might not be readable. Check manually whether the file share is accessible/readable by running the `xcp show` command
|Could not load file servers
|Try a page refresh. If the problem persists, manually run the `xcp show` command on the prompt and check whether you can scan the file server. If successful, raise a ticket with NetApp customer support. If unsuccessful, check manually to see if the file server is active

Check whether the `xcp.ini` file and license files are in the correct location. To reset the `xcp.ini` file, run the configuration script and select the *Repair* option. Next, select the menu option to *rebuild xcp.ini file.*

Check the xcpfalogs logs to see if the license needs renewal
|XCP File Analytics page is not displayed after system reboot
|XCP services might be down. Run the configuration script and select the option to *Repair*. This will restart all the services that are stopped
|The total space for an exported file system on a given file server might show more space compared to the allocated physical storage.
|This can happen when there are qtree level exports inside the volume.
For example, if the volume size is 10 GB that is exported as `/vol1` and there is a qtree inside the volume `/vol1/qtree1`, then the `xcp show` command will show the `vol1` size as `10 GB` and the `qtree1` size as `10 GB`. XCP File Analytics sums the space of both exports and gives the total space, in this case, `20 GB`. It does not understand that `qtree1` is a logical space.
|===
