---
sidebar: sidebar
permalink: xcp-nfs-reference-sync.html
keywords: netapp, xcp, reference, nfs, command, commands
summary: XCP NFS command reference
---

= sync 
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[lead]
The XCP NFS `sync` command scans for changes and modifications a source NFS directory using a catalog index tag name or the number of a previous copy operation. Incremental changes to the source are copied and applied to the target directory. The old catalog index numbers are replaced with new ones after the sync operation.

NOTE: During the sync operation, modified files and directories are copied to the destination NFSv3 export again.

.Syntax
[source,cli]
xcp sync -id <catalog_name>

.Show example
[%collapsible]
====
<enter_example>
====

== Parameters

The following table lists the `sync` parameters and their description.

[cols=2*,options="header"]
|===
| Parameter
| Description
| `sync -id <catalog_index>` | Specifies the catalog name of a previous copy index.
| `sync -nonames` | Excludes user and group names for file listings and reports.
| `sync -bs <n[k]>` | Specifies the read/write block size (default: 64k).
| `sync -dircount <n[k]>` | Specifies the request size when reading directories.
| `sync -parallel <n>` | Specifies the maximum number of concurrent batch processes (default: 7). 
| `sync -preserve-atime` | Restores all files to the last accessed date on the source.

|===


== Use sync command parameters

This section provides the parameters, descriptions, and examples for the XCP NFS `sync` command

=== Specify the catalog name of a previous copy index

You can specify the catalog name of previous copy index by using the `-id <catalog_name>` parameter.

.Syntax

[source,cli]
xcp sync -id <catalog_name> 

.Show example
[%collapsible]
====
<enter_example>
====


=== Exclude user and group names for file listings or reports

You can exclude user and group names for file listings or reports by using the `-id <catalog_name> and `-nonames` parameters.

.Syntax

[source,cli]
xcp sync -id <catalog_name> -nonames 

.Show example
[%collapsible]
====
<enter_example>
====

=== Specify the read/write block size

You can specify the read/write block size using the `-id <catalog_name>` and `-bs <n[k]>` parameters. The default block size is 64k. 

.Syntax

[source,cli]
xcp sync -id <catalog_name> -bs <n[k]>

.Show example
[%collapsible]
====
<enter_example>
====

=== Specify the request size when reading directories

You can specify the request size when reading directories by using the `-id <catalog_name>` and `-dircount <n[k]>` parameters. The default value is 64k.

.Syntax

[source,cli]
xcp sync -id <catalog_name> -dircount <n[k]>

.Show example
[%collapsible]
====
<enter_example>
====

=== Specify the maximum number of concurrent batch processes 

You can specify the maximum number of concurrent patch processes by using the `-id <catalog_name>` and `- parallel <number>` parameters. The default value is 7.

.Syntax

[source,cli]
xcp sync -id <catalog_name> -parallel <n> 

.Show example
[%collapsible]
====
<enter_example>
====

=== Restore all files to the last accessed date on the source

You can restore all files to the last accessed date on the source by using the `-id <catalog_name>` and `-preserve-atime` parameters. 

The `-preserve-atime` option resets the access time to the original value set before the XCP read operation.

.Syntax

[source,cli]
xcp sync -id <catalog_name> -preserve-atime 

.Show example
[%collapsible]
====
<enter_example>
====
