---
sidebar: sidebar
permalink: xcp-troubleshoot-xcp-smb-errors.html
keywords: netapp, xcp, troubleshoot, troubleshooting, smb,
summary: Troubleshooting XCP SMB Errors
---

= Troubleshoot XCP SMB Errors
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Review the solutions to troubleshoot your issue.

[options="header"]
|===
|Issue |Solution
a| XCP commands do not show the expected results when a junction path is used in the source or destination.

a| Use an SMB share path instead of a junction path when running XCP commands.
a| A traceback error might occur if the source, destination, or both is a junction with no directories and an online license is used in migration. If this occurs, the XCP command status is `PASSED` but the following error is returned at the end of the console output:
----
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "xcp\stats.py", line 214, in call_home
  File "xcp\histograms.py", line 387, in calculate_averages
ZeroDivisionError: division by zero
----
| Use an offline license instead of an online license. 
|`xcp: ERROR`: This license has expired
|Renew or obtain the new XCP license from the link:https://xcp.netapp.com/[XCP site^].
|This copy is not licensed
|Obtain the appropriate XCP license file. Copy the XCP license to the `c:\netapp\xcp` folder on the XCP host. Run the `xcp activate` command to activate the license
|`xcp: ERROR`: XCP not activated, run 'activate' first
|Download the XCP license from the link:https://xcp.netapp.com/[XCP site^]. Copy the file on the XCP Linux client host at `c:\netapp\xcp` on the XCP host. Run the `xcp activate` command to activate the license.
|`xcp: ERROR`: License file C:\NetApp\XCP\license not found
|Register for the XCP license on the link:https://xcp.netapp.com/[XCP site^]. Download and copy the license file to `C:\NetApp\XCP\` on the XCP Windows client host.
|xcp scan Error: The network name cannot be found
|Rerun the command with correct share name
|xcp copy Error: ERROR failed to obtain fallback security principal

Error message logged in xcp.log file:
`pywintypes.error: (1722, 'LookupAccountName', 'The RPC server is unavailable.')`
|Add the destination box in the hosts file (`C:\Windows\System32\drivers\etc\hosts`).
Netapp storage destination box entry must be in the below format:
`<data vserver data interface ip>` 1 or more white spaces `<cifs server name>`
|`xcp copy: ERROR` failed to obtain fallback security principal (Post adding destination box entry in the hosts files)

Error messaged logged in xcp.log file:
`'No mapping between account names and security IDs was done'`
|The fallback user/group does not exist at the target system (destination box) or active directory.

Rerun the command with correct fallback user/group options
|`xcp copy: ERROR` failed to obtain fallback security principal (Post adding destination box entry in the hosts files)

Error messaged logged in xcp.log file:
`pywintypes.error: (87, 'LookupAccountName', 'The parameter is incorrect.')`
|Incorrect parameter for fallback user/group option.
Rerun the command with the correct syntax for fallback user/group options
|`xcp copy` with ACL migration

Error message logged in xcp.log file:
`pywintypes.error`: `(1314, 'GetNamedSecurityInfo', 'A required privilege is not held by the client.')`
|An issue related to security descriptors because the migration user account only has the required privileges for XCP to retrieve owner, group, and DACL. It cannot retrieve SACL.
Add your migration user account to the "Manage Audit and Security Log” policy in your Active Directory.
Reference: link:https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/dn221953%28v%3Dws.11%29[Manage auditing and security log^]
|===

// 23 Oct 2023, OTHERDOC-34
// 2023 Aug 4, OTHERDOC-25