---
sidebar: sidebar
permalink: xcp-unsupported-features.html
keywords: xcp, nfs, smb, features, unsupported, configuration
summary: Some features are not supported on XCP NFS or XCP SMB.
---
= Unsupported features
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The following features are not supported on XCP NFS:

[cols="40,60"options="header"]
|===
|Feature Name |Description

|IPv6
|Does not support IP version 6 (IPv6)
|NFSv4 access control lists (ACLs) (third-party)
|Does not support third-party to NetApp NFSv4 ACLs
|POSIX connector
a|* The `sync` command does not support the POSIX connector
* You should not use the `copy` command when the source is active
|Hadoop Distributed File System (HDFS) connector
a|* The `sync` command does not support the HDFS connector
* The HDFS file system does not support symbolic links (symlinks), hard links, or special files
* You should not use the `copy` command when the source is active
|ACLs
|When the source is a non-NetApp system, XCP does not copy ACLs.
|Linux
|XCP is no longer supported on earlier distributions of Linux that were supported by XCP 1.6.3.

|===

The following features are not supported on XCP SMB:

[cols="40,60"]
|===
|Feature Name |Description

|NFS symbolic link (symlink)
|NFS symlink is not supported in XCP SMB
|ACL option for scan
|ACLs not supported for scan option
|IPv6
|Does not support IP version 6 (IPv6)
|NTFS Alternate Data Streams
|XCP does not currently support Alternate Data Streams
|XCP Filters
|The XCP SMB exclude option currently excludes directories based on their pattern in the filter and traverses the filesystem of those directories.
|Active source support
|XCP does not support the use of a baseline or an incremental Snapshot copy followed by live source migration for an incremental sync.
| Live source migration
| XCP does not support modifying data on the source volume during migration.
|===

The following common features are not available for XCP NFS and SMB:

*	*XCP multiple instances on same host*: When running multiple instances of XCP on the same host you might get unpredictable results.
*	*Time to complete migration*: XCP upfront does not provide the time to complete the migration or the time to complete any command used for migration. If you are doing final cutover confirm that data churn on the source volume is low.
* *Running copy again on an uncleaned target*: XCP baseline copy will fail when there is partial data on the destination target. For a successful XCP baseline copy and XCP verify, the destination must be clean.
* *Live destination*: XCP does not support modifying data on the destination volume during a migration or during an incremental sync.
* *Non-root user for File Analytics*: XCP does not support installations and configurations performed by a non-root user or a sudo user.

// BURT 1391465 05/31/2021
// BURT 1423222 09/13/2021
