---
sidebar: sidebar
permalink: xcp-unsupported-features.html
keywords: netapp, xcp, about, features, unsupported, supported, configuration
summary: NetApp XCP allows for scalable and high-performance data migrations
---
= Unsupported features
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The following features are not supported on XCP NFS:

[cols="40,60"]
|===
|Feature Name |Description

|IPv6
|Does not support IP version 6 (IPv6)
|NFSv4 ACLS (third-party)
|Does not support third-party to NetApp NFSv4 ACLs
|===

The following features are not supported on XCP SMB:

[cols="40,60"]
|===
|Feature Name |Description

|NFS symbolic link (symlink)
|NFS symlink is not supported in XCP SMB
|ACL option for scan
|ACLs not supported for scan option
|IPv6
|Does not support IP version 6 (IPv6)
|NTFS Alternate Data Streams
|XCP does not currently support Alternate Data Streams
|XCP Filters
|The XCP SMB exclude option currently excludes directories based on their pattern in the filter and traverses the filesystem of those directories.
|===

The following common features are not available for XCP NFS and SMB:

* *Active source support*: When data is active and continuously changing on the source volume. In such cases, use Snapshot for the data migration or perform the migration when there is no data changes happening on the source.
*	*XCP multiple instances on same host*: When running multiple instances of XCP on the same host you might get unpredictable results.
*	*Time to complete migration*: XCP upfront does not provide the time to complete the migration or the time to complete any command used for migration. If you are doing final cutover confirm that data churn on the source volume is low.
* *Running copy again on an uncleaned target*: XCP baseline copy will fail when there is partial data on the destination target. For a successful XCP baseline copy and XCP verify, the destination must be clean.
* *Live destination*: XCP does not support modifying data on the destination volume during a migration or during an incremental sync.

//BURT 1391465 05/31/2021
