---
sidebar: sidebar
permalink: xcp-nfs-reference-copy.html
keywords: netapp, xcp, reference, nfs, command, commands
summary: XCP NFS command reference
---

= copy
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[lead]
The XCP NFS `copy` command scans and copies the entire source directory structure to a destination NFSv3 export.

The `copy` command requires having source and destination paths as variables. The scanned and copied files, throughput, speed, and elapsed time details are displayed in the command output.

[NOTE]
====
* The runtime log file is located in `/opt/NetApp/xFiles/xcp/xcp.log` This path is configurable. Additional logging is located in the catalog after each command is run.
* If the source is a 7-Mode system, you can use a Snapshot copy as a source. For example: `<ip_address>:/vol/ex_s01/.snapshot/<snapshot_name>`
====

.Syntax
[source,cli]
copy <source_nfs_export_path> <destination_nfs_export_path>

.Show example
[%collapsible]
====
<enter_example>
====

== Parameters

The following table lists the `copy` parameters and their description.

[cols=2*,options="header"]
|===
| Parameter
| Description
| `copy -nonames` | Excludes user and group names for file listings and reports.
| `copy -match <filter>` | Only processes files and directories that match the filter.
| `copy -md5 <string_expression>` | Generates checksums on the files and saves the checksums when indexing (default: false). 
| `copy -dircount <n[k]>` | Specifies the request size when reading directories.
| `copy -edupe` | Includes the dedupe estimate in reports.
| `copy -bs <n[k]>` | Specifies the read/write block size (default: 64k).
| `copy -parallel <n>` | Specifies the maximum number of concurrent batch processes (default: 7). 
| `copy -acl4` | Processes NFSv4 access control lists (ACLs).
| `copy -preserve-atime` | Restores all files to the last accessed date on the source.
| `copy -s3.insecure` | Provides the option to use HTTP instead of HTTPS for S3 bucket communication.
| `copy -s3.endpoint <s3_endpoint_url>` | Overrides the default Amazon Web Services (AWS) endpoint URL with the specified URL for S3 bucket communication.
| `copy -s3.profile <profile_name>` | Specifies a profile from the AWS credential file for S3 bucket communication.
| `copy -s3.noverify` | Overrides the default verification of SSL certification for S3 bucket communication.

|===


== Use copy command parameters

This section provides the parameters, descriptions, and examples for the XCP NFS `copy` command


=== Exclude user and group names for file listings or reports

You can exclude user and group names for file listings or reports by using the `-nonames` parameter.

.Syntax

[source,cli]
xcp copy -nonames <source_ip_address_or_hostname>:/<source_vol> <destination_ip_address_or_hostname>:/<dest_vol>

.Show example
[%collapsible]
====
<enter_example>
====

=== Only process the files and directories that match the filter

You can specify that only the files and directories that match a filter are processed by using the `-match <filter>` parameter.

.Syntax 

[source,cli]
xcp copy -match <filter> <source_ip_address_or_hostname>:/<source_vol> <destination_ip_address_or_hostname>:/<dest_vol>

.Show example
[%collapsible]
====
<enter_example>
====

=== Generate checksums for file listings and save the checksums when indexing

You can generate checksums for the file listings and save the checksums when indexing by using the `-md5` parameter. The default value is set to false.

.Syntax

[source,cli]
xcp copy -md5 <source_ip_address_or_hostname>:/<source_vol> <destination_ip_address_or_hostname>:/<dest_vol>

.Show example
[%collapsible]
====
<enter_example>
====


=== Specify the request size when reading directories

You can specify the request size when reading directories by using the `-dircount <number>` parameter. The default value is 64k.

.Syntax

[source,cli]
xcp copy -dircount 32k <source_ip_address_or_hostname>:/<source_vol> <destination_ip_address_or_hostname>:/<dest_vol>

.Show example
[%collapsible]
====
<enter_example>
====

=== Include the deduplication estimate in reports

You can include the deduplication estimate in reports by using the `-edupe` parameter.

.Syntax

[source,cli]
xcp copy -edupe <source_ip_address_or_hostname>:/<source_vol> <destination_ip_address_or_hostname>:/<dest_vol>

.Show example
[%collapsible]
====
<enter_example>
====

=== Specify the read/write block size

You can specify the read/write block size using the `-bs <number>` parameter. The default block size is 64k. 

.Syntax

[source,cli]
xcp copy -bs <number> <ip_address_or_hostname>:/<source_vol> <destination_ip_address_or_hostname>:/<dest_vol>

.Show example
[%collapsible]
====
<enter_example>
====

=== Specify the maximum number of concurrent batch processes 

You can specify the maximum number of concurrent patch processes by using the `- parallel <number>` parameter. The default value is 7.

.Syntax

[source,cli]
xcp copy -parallel <number> <ip_address_or_hostname>:/<source_vol> <destination_ip_address_or_hostname>:/<dest_vol>

.Show example
[%collapsible]
====
<enter_example>
====

=== Process NFSv4 access control lists (ACLs)

You can process NFSv4 ACLs by using the `-acl4` parameter. 

.Syntax

[source,cli]
xcp copy -acl4 <ip_address_or_hostname>:/<source_vol> <destination_ip_address_or_hostname>:/<dest_vol>

.Show example
[%collapsible]
====
<enter_example>
====

=== Restore all files to the last accessed date on the source

You can restore all files to the last accessed date on the source by using the `-preserve-atime` parameter. 

The `-preserve-atime` option resets the access time to the original value set before the XCP read operation.

.Syntax

[source,cli]
xcp copy -preserve-atime <source_ip_address_or_hostname>:/<source_vol> <destination_ip_address_or_hostname>:/<dest_vol>

.Show example
[%collapsible]
====
<enter_example>
====

=== Use HTTP instead of HTTPS for S3 bucket communication

You can use HTTP instead of HTTPS for S3 bucket communication by using the `-s3.insecure` parameter. 

.Syntax

[source,cli]
xcp copy -s3.insecure hdfs://<hdfs_path> s3://<bucket_name>

.Show example
[%collapsible]
====
<enter_example>
====

=== Override the default Amazon Web Services (AWS) endpoint URL with the specified URL for S3 bucket communication

You can override the default AWS endpoint URL with the specified URL for S3 bucket communication by using the `-s3.endpoint <s3_endpoint_url>` parameter. 

.Syntax

[source,cli]
xcp copy -s3.endpoint https://<endpoint_url>: hdfs://<hdfs_path> s3://<bucket_name>

.Show example
[%collapsible]
====
<enter_example>
====

=== Specify a profile from the AWS credential file for S3 bucket communication

You can specify a profile from the AWS credential file for S3 bucket communication by  using the `-s3.profile <profile_name>` parameter. 

.Syntax

[source,cli]
xcp copy -s3.profile <name> -s3.endpoint https://<endpoint_url>: hdfs://<hdfs_path> s3://<bucket_name>

.Show example
[%collapsible]
====
<enter_example>
====

=== Override the default verification of SSL certification for S3 bucket communication 

You can override the default verification of SSL certification for S3 bucket communication by using the `-s3.noverify` parameter. 

.Syntax

[source,cli]
xcp copy -s3.noverify hdfs://<hdfs_path> s3://<bucket_name>

.Show example
[%collapsible]
====
<enter_example>
====

