---
sidebar: sidebar
permalink: xcp-migrate-nfs-additional-features.html
keywords: xcp, nfs, chomod, chown, posix, ownership, change, file, path, directory, command, scan
summary: XCP includes some additional NFS features that make it easy to change the ownership and permissions of files and directories for any NFS share or POSIX path.
---

= Additional NFS features

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

XCP includes some additional NFS features.

== Chown and Chmod

You can use the XCP `chown` and `chmod` commands to recursively change all of the files and directories for a given NFS share or POSIX path. This increases the performance of millions of files.

NOTE: Before changing the ownership of the files, you must configure the new owner. Otherwise, the command will fail. The XCP `chown` and `chmod` commands work similar to the Linux `chown` and `chmod` commands.

=== Chmod

The `chmod` command scans and changes the file permission of all files in the chosen directory structure. The `chmod` command requires a mode or reference and an NFS share or POSIX path as variables. XCP `chmod` recursively changes the permissions for a given path. You can use the `chmod` command to display the total files scanned and the permissions that have been changed in the output.

*Example:*
....
xcp chmod -mode 777 NFS [server:/export path | file://<NFS mounted path>]
xcp chmod -mode 707 nfs_server01.netapp.com:/export1
xcp chmod -reference nfs_server01.netapp.com:/export/dir1/file.txt  nfs_server02.netapp.com: export1
xcp chmod -match “fnm(‘file.txt’)” -mode 111 file:///mnt/nfs_mount_point/
xcp chmod -exclude “fnm(‘file.txt’)” -mode 111 file:///demo/user1/
....

Run the `xcp help chmod` command for more information.

=== Chown

You can use the XCP `chown` command to recursively change all of the files and directories for a given NFS share or POSIX path. This increases the performance of millions of files.

The `chown` command scans and changes the ownership of all files in the chosen directory structure. The `chown` command requires an NFS share or POSIX path as variables. XCP `chown` recursively changes the ownership for a given path.

*Example*
....
xcp chown -user user1 NFS [server:/export path | file://<NFS mounted path>
xcp chown -user user1 nfs_server01.netapp.com:/export1
xcp chown -user user1 -group group1 nfs_server01.netapp.com:/export1/dir1/
xcp chown  -reference nfs_server01.netapp.com:/export/dir1/file.txt  nfs_server02.netapp.com:/export1
xcp chown -match “fnm(‘file.txt’)” -user user1 file:///mnt/nfs_mount_point/
xcp chown -exclude “fnm(‘file.txt’)” -user user1 -group group1
xcp chown -user-from user1 -user user2 file:///mnt/nfs_mount_point/
xcp chown -group-from group1 -group group2 nfs_server01.netapp.com:/export1/
....

Run the `xcp help chown` command for more information.

== XCP Estimation

The XCP estimation feature estimates the time to complete a baseline `copy` operation from the source to the destination. It calculates the estimated time to complete a baseline `copy` operation by using all the currently available system resources such as CPU, RAM, network, or other parameters. When you use the `-target` option, XCP runs a sample copy operation to find the estimation time.

*Example*
....
server : NFS server IP
export : NFS exported path for the above IP

xcp static estimation
xcp estimate -id <scan id>

xcp live estimation with default time
xcp estimate -id <scan id> -target server:/export

xcp live estimation with -t option
xcp estimate -id <scan id> -t <time for which estimation should run> -target server:/export
....

== indexdelete

The XCP `indexdelete` command can be used to delete catalog indexes.

*Example*

----
[root@client1 linux]# ./xcp indexdelete 
XCP <version> (c) 2023 NetApp, Inc.; Licensed to xxx [Network Appliance, Inc] until Tue Jul 23 04:32:03 2024

Job ID: Job_2023-11-16_02.41.20.260166_indexdelete
===========================================================================================
Name                                    Command   Size      Created      Updated           
===========================================================================================
isync_tc1_retry                         copy      996 KiB   15-Nov-2023  15-Nov-2023       
isync_est_isync                         isync     1012 KiB  15-Nov-2023  15-Nov-2023       
XCP_verify_2023-11-15_05.56.17.522428   verify    1016 KiB  15-Nov-2023  15-Nov-2023       
XCP_verify_2023-11-15_06.04.31.693517   verify    1.00 MiB  15-Nov-2023  15-Nov-2023       
isync_tc1_retry1                        copy      988 KiB   15-Nov-2023  15-Nov-2023       
XCP_verify_2023-11-15_09.02.46.973624   verify    988 KiB   15-Nov-2023  15-Nov-2023       
est001                                  isync     1012 KiB  15-Nov-2023  15-Nov-2023       
XCP_verify_2023-11-15_09.37.24.179634   verify    0         15-Nov-2023  15-Nov-2023       
a1batch_error1                          copy      368 KiB   15-Nov-2023  15-Nov-2023       
XCP_verify_2023-11-15_09.45.53.104055   verify    360 KiB   15-Nov-2023  15-Nov-2023       
a1batch_error2                          isync     376 KiB   15-Nov-2023  15-Nov-2023       
XCP_verify_2023-11-15_09.48.05.000473   verify    372 KiB   15-Nov-2023  15-Nov-2023       
b1batch_error1                          copy      4.50 KiB  15-Nov-2023  15-Nov-2023       
XCP_verify_2023-11-15_12.00.29.214479   verify    4.50 KiB  15-Nov-2023  15-Nov-2023       
b1batch_error2                          isync     4.50 KiB  15-Nov-2023  15-Nov-2023       
XCP_verify_2023-11-15_12.00.40.536687   verify    4.50 KiB  15-Nov-2023  15-Nov-2023       
XCP_verify_2023-11-15_12.27.08.055501   verify    4.50 KiB  15-Nov-2023  15-Nov-2023       
XCP_verify_2023-11-15_12.27.39.797020   verify    4.50 KiB  15-Nov-2023  15-Nov-2023       
XCP_verify_2023-11-15_12.52.29.408766   verify    4.50 KiB  15-Nov-2023  15-Nov-2023       
XCP_verify_2023-11-15_12.53.01.870109   verify    4.50 KiB  15-Nov-2023  15-Nov-2023       
c1batch_error1                          copy      988 KiB   15-Nov-2023  15-Nov-2023       
XCP_verify_2023-11-15_22.54.11.081944   verify    976 KiB   15-Nov-2023  15-Nov-2023       
c1batch_error2                          isync     1020 KiB  15-Nov-2023  15-Nov-2023       
XCP_verify_2023-11-15_23.19.44.158263   verify    1.00 MiB  15-Nov-2023  15-Nov-2023       
XCP_verify_2023-11-15_23.44.01.274732   verify    4.50 KiB  15-Nov-2023  15-Nov-2023       
c1batch_error132576                     copy      992 KiB   16-Nov-2023  16-Nov-2023       
c1batch_error227998                     isync     1004 KiB  16-Nov-2023  16-Nov-2023       
XCP_verify_2023-11-16_01.07.45.824516   verify    1012 KiB  16-Nov-2023  16-Nov-2023       
S3_index                                copy      52.5 KiB  16-Nov-2023  16-Nov-2023       
S3_index1                               copy      52.5 KiB  16-Nov-2023  16-Nov-2023       
c1batch_error14383                      copy      728 KiB   16-Nov-2023  16-Nov-2023       

32 scanned, 941 KiB in (1.04 MiB/s), 48.8 KiB out (55.4 KiB/s), 0s.

WARNING: 31 indexes will be deleted permanently.
Are you sure you want to delete (yes/no): yes


Xcp command : xcp indexdelete
Stats       : 466 scanned, 31 index deleted
Speed       : 1.09 MiB in (216 KiB/s), 133 KiB out (25.8 KiB/s)
Total Time  : 5s.
Job ID      : Job_2023-11-16_02.41.20.260166_indexdelete
Log Path    : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-11-16_02.41.20.260166_indexdelete.log
STATUS      : PASSED
[root@client1 linux]#

----
// 1455556, 2022-02-11
// 1483343, 2022-06-17
// 2023-04-20, OTHERDOC-7