---
sidebar: sidebar
permalink: xcp-prepare-windows-for-xcp-smb.html
keywords: netapp, xcp, prepare, preparing, preparation, windows,
summary: Prepare Windows for XCP SMB
---

= Prepare Windows for XCP SMB
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
XCP SMB uses Windows client host systems to generate parallel I/O streams and fully use available network and storage performance.

== Configure storage

XCP SMB transitions and migrations have the following user login requirements:

*	XCP host system: An XCP host user must have administrator privilege (the user must be part of "BUILTIN\Administrators" group on the XCP SMB host system).
*	Add the migration or XCP host user to the audit and security log policy for Active Directory. To locate the 'Manage Auditing and Security Log' Policy on Windows 10, follow these steps:
+
.Steps

.	Open the *Group Policy Editor* dialog box.
.	Go to *Computer Configuration > Windows Settings > Security Settings > Local Policies > User Rights Assignment*.
.	Select *Mange auditing and security log*.
.	To add an XCP host user, select *Add User or Group*.
+
For more information, see: link:https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/dn221953(v%3Dws.11)[Manage auditing and security log^].

*	Target storage system: XCP host user must have read and write access.
*	Source storage system:
**	If the user is part of the “Backup Operators” group in the source storage system, the
members of this group can read files while bypassing the security rules,
regardless of any permissions that protect those files.
**	If the user is not part of “Backup Operators” group in source system, the user
must have read access.

NOTE: Write permission is required in the source storage system for supporting the XCP option `- preserve-atime`.

== Configure a Windows client

* Add the destination storage box and the source storage box to the host file:
+
. Navigate to the following location: `(C:\Windows\System32\drivers\etc\hosts)`
. Insert the following host entries to the file in the below format:
+

`<Source data vserver data interface ip>   <Source cifs server name>  <Destination data vserver data interface ip>   <Destination cifs server name>`
+
*Example*
+
----
Copyright (c) 1993-2009 Microsoft Corp.

This is a sample HOSTS file used by Microsoft TCP/IP for windows.

This file contains the mappings of IP addresses to host names. Each entry should be kept on an individual line. The IP address should be placed in the first column followed by the corresponding host name. The IP address and the host name should be separated by at least one space.

Additionally, comments (such as these) may be inserted on individual lines or following the machine name denoted by a `#` symbol.

 For example:

     102.54.94.97   rhino.acme.com   # source server
      38.25.63.10   x.acme.com       # x client hosts

 localhost name resolution is handled within DNS itself.
      127.0.0.1      localhost
      ::1            localhost

10.237.161.197 00906A52DFE247F
10.237.170.5  42D1BBE1219CE63
----

//BURT 1445538, 2022-02-07
