---
sidebar: sidebar
permalink: xcp-smb-reference-verify.html
keywords: netapp, xcp, reference, smb, command, commands
summary: XCP SMB "verify" command reference
---
= verify
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The `verify` command reads and compares the source and target shares and provides information about what is different. You can use the `verify` command on any source and destination, regardless of the tool used to perform the copy or sync operation.

.Syntax
[source,cli]
xcp verify \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

.Show example
include::./_include/ref-example-smb-verify.adoc[]

The following table lists the `verify` parameters and their description.

[cols=2*,options="header"]
|===
| Parameter | Description

| <<smb_verify_help, verify -h, --help>> | Show this help message and exit.
| <<verify -v>> | Increase debug verbosity.
| <<smb_verify_parallel, verify -parallel <n> >> | Number of concurrent processes (default: <cpu-count>).
| <<smb_verify_match, verify -match <filter> >> | Only process files and directories that match the filter (see `xcp help - match` for details).
| <<smb_verify_exclude,verify -exclude <filter> >> | Only exclude files and directories in the filter.
| <<verify -preserve-atime>> | Restore last accessed date on source.
| <<verify -nodata>> | Do not check data.
| <<verify -atime>> | Verify file access time.
| <<verify -noctime>> | Do not check file creation time.
| <<verify -nomtime>> | Do not check file modification time.
| <<verify -noattrs>> | Do not check attributes.
| <<verify -noownership>> | Do not check ownership.
| <<verify -ads>> | Scan for changes and modifications of alternate data streams in the source and target SMB share. If there are changes, it applies the change to the target to 
make sure that the target is identical to the source.
| <<verify -noacls>> | Do not check ACLs.
| <<verify_smb_atime, verify -atimewindow <float> >> | Acceptable access time difference, in seconds.
| <<verify_smb_ctime, verify -ctimewindow <float> >> | Acceptable creation time difference, in seconds.
| <<verify_smb_mtime, verify -mtimewindow <float> >> | Acceptable modification time difference, in seconds,
| <<verify -stats>> | Scan source and target trees in parallel and compare tree statistics.
| <<verify -l>> | Increases output detail.
| <<verify -ll>> | Increases output detail (git diff format).
| <<verify_smb_acl, verify -fallback-user FALLBACK_USER >> 
| Active Directory user or local(non-domain) user on the target machine to receive the permissions of local (non-domain) source machine users (example: domain\administrator).
| <<verify_smb_acl, verify -fallback-group FALLBACK_GROUP >>
| Active Directory group or local(non-domain) group on the target machine to receive the permissions of local(non-domain) source machine groups (example: domain\administrators).
| <<smb_verify_root,verify -root>> | Sync ACLs for the root directory.
| <<verify_smb_onlyacl, verify -onlyacl>> | Copy only the security information.

|=== 

[[smb_verify_help]]
== verify -h, --help
Use the `-h` and `–-help` parameters with the `verify` command to display detailed information about the `verify` command

.Syntax
[source,cli]
xcp verify –help

.Show example
include::./_include/ref-example-smb-verify-help.adoc[]

== verify -v
Use the `-v` parameter with the `verify` command to provide detailed debug information.

.Syntax
[source,cli]
xcp verify -v \\<IP address of SMB source server>\source_share address of SMB destination server>\dest_share

.Show example
include::./_include/ref-example-smb-verify-v.adoc[]

[[smb_verify_parallel]]
==  verify -parallel <n>
Use the `-parallel <n>` parameter with the `verify` command to set a higher or lower number of XCP concurrent processes. The `verify -parallel <n>` command verifies the number of concurrent processes (default: <cpu-count>).

NOTE: The maximum value for n is 61. 

.Syntax
[source,cli]
xcp verify -v -parallel <n> \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

.Show example
include::./_include/ref-example-smb-verify-parallel.adoc[]

[[smb_verify_match]]
== verify -match <filter>
Use the `-match <filter>` parameter with the `verify` command to scan the source and target tree and compare only the files or directories that match the filter argument. If there are any differences, the command applies the required actions on the target to keep them in sync.

.Syntax
[source,cli]
xcp verify -v -match <filter> \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

.Show example
include::./_include/ref-example-smb-verify-match.adoc[]


[[smb_verify_exclude]]
== verify -exclude <filter>

Use the `-exclude <filter>` parameter with the `verify` command to only exclude files and directories in the filter.

.Syntax
[source,cli]
xcp verify -exclude <filter> \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

.Show example
include::./_include/ref-example-smb-verify-exclude.adoc[]

== verify -preserve-atime 
Use the `-preserve-atime` parameter with the `verify` command to reset `atime` to the original value before XCP read the file.

.Syntax
[source,cli]
xcp verify -preserve-atime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

.Show example
include::./_include/ref-example-smb-verify-preserveatime.adoc[]

== verify -nodata
Use the `-nodata` parameter with the `verify` command to not compare data.

.Syntax
[source,cli]
xcp verify -nodata \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

.Show example
include::./_include/ref-example-smb-verify-nodata.adoc[]

== verify -atime
Use the `-atime` parameter with the `verify` command to compare file access time stamps from the source to destination.

.Syntax
[source,cli]
xcp verify -ll -atime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

.Show example
include::./_include/ref-example-smb-verify-atime.adoc[]

== verify -noctime
Use the `-noctime` parameter with the `verify` command to not compare file creation time stamps from the source to destination.

.Syntax
[source,cli]
xcp verify -noctime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

.Show example
include::./_include/ref-example-smb-verify-noctime.adoc[]

== verify -nomtime
Use the `-nomtime` parameter with the `verify` command to not compare file modification time stamps from the source to destination.

.Syntax
[source,cli]
xcp verify -nomtime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

.Show example
include::./_include/ref-example-smb-verify-nomtime.adoc[]

== verify -noattrs
Use the `-noattrs` parameter with the `verify` command to not check attributes.

.Syntax
[source,cli]
xcp verify -noattrs \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

.Show example
include::./_include/ref-example-smb-verify-noattrs.adoc[]

== verify -noownership
Use the `-noownership` parameter with the `verify` command to not check ownership.

.Syntax
[source,cli]
xcp verify -noownership \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

.Show example
include::./_include/ref-example-smb-verify-noownership.adoc[]

== verify -ads
Using `-ads` parameter with the `verify` command to read if there are any alternate data streams on the source and destination and display any differences.

.Syntax
[source,cli]
xcp verify -ads \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

.Show example
include::./_include/ref-example-smb-verify-ads.adoc[]

== verify -noacls
Use the `-noacls` parameter with the `verify` command to not check ACLs.

.Syntax
[source,cli]
xcp verify -noacls -noownership \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

.Show example
include::./_include/ref-example-smb-verify-noacls.adoc[]

=== verify -noacls -noownership

Use the `-noownership` parameter with `verify -noacls`  to not check ACLs or ownership from the source to the destination.

.Syntax
[source,cli]
xcp verify -noacls -noownership <source> <target>

[[verify_smb_atime]]
== verify -atimewindow <float>
Use the `-atimewindow <float>` parameter with the `verify` command to specify the acceptable difference, in seconds, for the `atime` of a file from the source to the destination. XCP does not report files as being different if the difference in `atime` is less than <value>. The `verify - atimewindow` command can only be used with the `-atime` flag.

.Syntax
[source,cli]
xcp verify -atimewindow <float> \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

.Show example
include::./_include/ref-example-smb-verify-atimewindow.adoc[]

[[verify_smb_ctime]]
== verify -ctimewindow <float>
Use the `-ctimewindow <float>` parameter with the `verify` command to specify the acceptable difference, in seconds, for the `ctime` of a file from the source to the destination. XCP does not report files as being different when the difference in `ctime` is less than <value>.

.Syntax
[source,cli]
xcp verify -ctimewindow <float> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

.Show example
include::./_include/ref-example-smb-verify-ctimewindow.adoc[]

[[verify_smb_mtime]]
== verify -mtimewindow <float>
Use the `-mtimewindow <float>` parameter with the `verify` command to specify the acceptable difference, in seconds, for the `mtime` of a file from the source to the destination. XCP does not report files as being different when the difference in `mtime` is less than <value>.

.Syntax
[source,cli]
xcp verify -mtimewindow <float> \\<IP address of SMB sourceserver>\source_share \\<IP address of SMB destination server>\dest_share

.Show example
include::./_include/ref-example-smb-verify-mtimewindow.adoc[]

== verify -stats
Use the `-stats` parameter with the `verify` command to scan the source and the destination and print a tree statistics report showing similarities or differences between the two shares.

.Syntax
[source,cli]
xcp verify -stats \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

.Show example
include::./_include/ref-example-smb-verify-stats.adoc[]

== verify -l
Use the `-l` parameter with the `verify` command to list the differences between files and directories on the source and destination. 

.Syntax
[source,cli]
xcp verify -l \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

In the following example, during copy, the ownership information was not transferred, and you can see the differences in the command output.

.Show example
include::./_include/ref-example-smb-verify-l.adoc[]

== verify -ll

Use the `-ll` parameter with the `verify` command to list the detailed differences of the files or directories from the source and the target. The format is like git diff. The red value is the old one from the source, and the green value is the new one from the target.

.Syntax
[source,cli]
xcp verify -ll \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

.Show example
include::./_include/ref-example-smb-verify-ll.adoc[]

[[verify_smb_acl]]
== verify-fallback-user <fallback_user> -fallback-group <fallback_group>
Use the `-fallback-user` and `-fallback-group` parameters with the `verify` command to list the ACL and ownership differences between files and directories on the source and destination.

NOTE: If you use `fallback-user` and `fallback-group` with a copy or sync operation, NetApp recommends that you also use the `fallback-user` and `fallback-group` parameters with the verify operation.

.Syntax
[source,cli]
xcp verify -fallback-user <fallback_user> -fallback-group <fallback_group> \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

=== verify -noownership-fallback-user <fallback_user> -fallback-group <fallback_group>
Use the `-noownership,` `-fallback-user`, and `-fallback-group` parameters with the `verify` command to list the ACL differences and skip verification of ownership between files and directories on the source and destination.

.Syntax
[source,cli]
xcp verify -noownership -fallback-user <fallback_user> -fallback-group <fallback_group> \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

=== verify -noacls-fallback-user <fallback_user> -fallback-group <fallback_group>
Use the `-noacls`, `-fallback-user`, and `-fallback-group` parameters with the `verify` command to skip verification of ACLs and verify ownership between files and directories on the source and destination.

.Syntax
[source,cli]
xcp verify -noacls -fallback-user <fallback_user> -fallback-group <fallback_group> \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
 
[[smb_verify_root,verify -root]]
== verify -root
Use the `-root` parameter with the `verify` command to sync the ACLs for the root directory. 

.Syntax
[source,cli]
xcp verify -root -fallback-user <fallback_user> -fallback- group <fallback_group> \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

.Show example
include::./_include/ref-example-smb-verify-root.adoc[]

[[verify_smb_onlyacl]]
=== verify -onlyacl -fallback-user <fallback_user> -fallback- group <fallback_group> 
Use the `-onlyacl`, `-fallback-user` and `-fallback-group` parameters with the `verify` command to compare only the security information between the source and destination.

.Syntax
[source,cli]
xcp verify -onlyacl -preserve-atime -fallback-user <fallback_user> -fallback- group <fallback_group> \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

.Show example
include::./_include/ref-example-smb-verify-onlyacl.adoc[]
