---
sidebar: sidebar
permalink: xcp-nfs-reference-show.html
keywords: netapp, xcp, reference, nfs, command, commands
summary: XCP NFS command reference
---

= show
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[lead]
The NFS `show` command queries the RPC services and NFS exports of one or more storage servers. The command also lists the available services and exports and shows the used and free capacity of each export, followed by the attributes of the root of each export.

.Syntax

IMPORTANT: The `show` command requires the host name or IP address of the NFSv3 exported system.

[source,cli]
xcp show <ip_address_or_host_name>

.Show example
[%collapsible]
====
<enter_example>
====

.Parameters

The following table lists the `show` parameters and their description.

[cols=2*,options="header"]
|===
| Parameter
| Description
| show -v | Returns details about NFS servers using the IP address or host name.
|===

== Return details about NFS servers using the IP address or host name

The `show -v` command returns details about NFS servers using the IP address or host name.

.Syntax

[source,cli]
`xcp show -v`

.Show example
[%collapsible]
====
<enter_example>
====

