---
sidebar: sidebar
permalink: xcp-plan-data-migration.html
keywords:
summary:
---

= Plan data migration
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

You can plan your migration using the CLI or the File Analytics GUI.
Use the following commands to plan your migration:

*	Show
*	Scan

Use File Analytics to visualize the statistics for exports and shares.

== Plan NFS data migration

*Show*

The `show` command queries the RPC services and NFS exports of one or more storage servers. The command lists the available services and exports with the used and free capacity of each export, followed by the root attributes of each export.
Example:

        * `xcp show <NFS file server IP/FQDN>``
        * `xcp show nfs_server01.netapp.com`
Run `xcp help show` for more details.

*Scan*

The scan command recursively scans the entire source NFSv3 exported paths and prints the statistics of file structure at the end of the scancan. NetApp recommends putting the source NFS export mounts in read-only mode during the scan operation.
Example:

        * `xcp scan NFS server:/export path`
        * `xcp scan nfs_server01.netapp.com:/export1`
        
Run *xcp help scan* for more details.

Optionally, use File Analytics to view the results graphically.

== Plan SMB data migration

*Show*:

The `show` command shows all SMB shares available on the server with the permissions and space available.
Example:

        * `xcp show \\<SMB file server IP/FQDN>`
        * `xcp show smb_server01.netapp.com`

Run `xcp help show` for more details.

*Scan*:

The scan command recursively scans the entire SMB share and lists all the files at the end of the scan.
Example :

        * `xcp scan \\SMB server\share1`
        * `xcp scan smb_server01.netapp.com:/share1`

Run `xcp help scan` for more details.
.
Optionally, use File Analytics to view the results graphically.

== Plan using File Analytics

NOTE: XCP is a CLI, whereas File Analytics has a GUI.

*Overview*

XCP File Analytics uses the XCP scan API to collect data from NFS or SMB hosts. This data is then displayed on XCP File Analytics GUI. There are three main components involved in XCP File Analytics:

* XCP service
* File Analytics database
* File Analytics GUI to manage and view data

The deployment the method for XCP File Analytics components depends on the solution required:

*	Deploying XCP File Analytics solutions for NFS file systems:
** You can deploy the File Analytics GUI, database, and XCP service in the same Linux host.
*	Deploying XCP File Analytics solutions for SMB file systems:
You must deploy the File Analytics GUI and database in a Linux host and deploy the XCP service on a Windows host.
