---
sidebar: sidebar
permalink: xcp-install-xcp-nfs.html
keywords: netapp, xcp, install, installing, nfs
summary: Installing XCP NFS
---

= Install XCP NFS
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/
[.lead]
If you want to upgrade XCP, delete the current installation and replace it with a new installation of the latest version.
This section details the system requirements and the procedures for the initial setup of XCP on a Linux client and the INI file configuration.

*System Requirements*

[cols="35,65"]
|===
|Item |Requirement

|System
|64-bit Intel or AMD server, minimum 8 cores and 64 GB RAM
|Operating System & Software
|See the link:https://mysupport.netapp.com/matrix/[IMT^] for supported operating systems
|Special Requirements
|Network connectivity and root level access to source and destination NFSv3 exports

No other active applications
|Storage
|20 MB of disk space for the XCP binary and at least 50 MB of disk space for the logs that are stored in the /opt/NetApp/xFiles/xcp/ directory
|Supported Protocol Version
|NFSv3 and NFSv4 (POSIX and ACL)
|Supported browser (File Analytics only)
|Refer to the link:https://mysupport.netapp.com/matrix/[IMT^] matrix for all supported browser versions for XCP File Analytics.
|===

NOTE: The recommended configuration for live source migration is 8 cores and 64 GB RAM.

== Install XCP NFS for a root user

You can use the following procedure to install XCP for a root user.

.Steps

. Log in to the Linux machine as the root user and download and install the license:
+
----
[root@scspr1980872003 ~]# ls -l
total 36188
-rw-r--r--  1 root root 37043983 Oct  5 09:36 NETAPP_XCP_<version>.tgz
-rw-------. 1 root root     1994 Sep  4  2019 license
----
+
.	To extract the tool, untar XCP:
+
----
[root@scspr1980872003 ~]# tar -xvf NETAPP_XCP_<version>.tgz
[root@scspr1980872003 ~]# ls
NETAPP_XCP_<version>.tgz license xcp
[root@scspr1980872003 ~]# cd xcp/linux/
[root@scspr1980872003 linux]# ls
xcp
----
+
.	Verify that the `/opt/NetApp/xFiles/xcp` path is available on the system from a previous version of XCP.
+
If `/opt/NetApp/xFiles/xcp` is available, activate the license by using the `xcp activate` command and proceed with data migration.
+
If `/opt/NetApp/xFiles/xcp` is not available, when you run the `xcp activate` command is run for the first time, the system creates the XCP host configuration directory in `/opt/NetApp/xFiles/xcp`.
+
The `xcp activate` command fails because the license is not installed:
+
----
[root@scspr1980872003 linux]# ./xcp activate
(c) yyyy NetApp, Inc.
xcp: Host config file not found. Creating sample at '/opt/NetApp/xFiles/xcp/xcp.ini'

xcp: ERROR: License file /opt/NetApp/xFiles/xcp/license not found.
Register for a license at https://xcp.netapp.com
----
+
. Copy the license to `/opt/NetApp/xFiles/xcp/`:
+
----
[root@scspr1980872003 linux]# cp ~/license /opt/NetApp/xFiles/xcp/
----
+
.	Verify that the license file was copied to `/opt/NetApp/xFiles/xcp/`:
+
----
[root@ scspr1980872003 ~]# ls -altr /opt/NetApp/xFiles/xcp/
total 44
drwxr-xr-x 3 root root    17 Oct  1 06:07 ..
-rw-r--r-- 1 root root   304 Oct  1 06:07 license
drwxr-xr-x 2 root root     6 Oct  1 10:16 xcpfalogs
drwxr-xr-x 2 root root    21 Oct  1 10:16 xcplogs
-rw-r--r-- 1 root root   110 Oct  5 00:48 xcp.ini
drwxr-xr-x 4 root root    83 Oct  5 00:48 .
[root@scspr1978802001 ~]#
----
+
.	Activate XCP:
+
----
[root@scspr1980872003 linux]# ./xcp activate
XCP <version>; (c) yyyy NetApp, Inc.;
XCP activated
----

== Install XCP for a non-root user

You can use the following procedure to install XCP for a non-root user.

.Steps
.	Log in to the Linux machine as the non-root user and download and install the license:
+
----
[user1@scspr2474004001 ~]$ ls -l
total 36640
-rwxr-xr-x 1 user1 user1      352 Sep 20 01:56 license
-rw-r--r-- 1 user1 user1 37512339 Sep 20 01:56 NETAPP_XCP_Nightly_dev.tgz
[user1@scspr2474004001 ~]$
----

. To extract the tool, untar XCP:
+
----
[user1@scspr2474004001 ~]$ tar -xvf NETAPP_XCP_Nightly_dev.tar
[user1@scspr2474004001 ~]$ cd xcp/linux/
[user1@scspr2474004001 linux]$ ls
xcp
[user1@scspr2474004001 linux]$
----

.	Verify that the `/home/user1/NetApp/xFiles/xcp` path is available on the system from a previous version of XCP.
+
If the `/home/user1/NetApp/xFiles/xcp` path is available, activate the license by using the `xcp activate` command and proceeding with data migration.
+
If `/home/user1/NetApp/xFiles/xcp` is not available, when you run the `xcp activate` command for the first time, the system creates the XCP host configuration directory in `/home/user1/NetApp/xFiles/xcp`.
+
The `xcp activate` command fails because the license is not installed:
+
----
[user1@scspr2474004001 linux]$ /home/user1/xcp/linux/xcp activate
(c) yyyy NetApp, Inc.
xcp: Host config file not found. Creating sample at '/home/user1/NetApp/xFiles/xcp/xcp.ini'

xcp: ERROR: License file /home/user1/NetApp/xFiles/xcp/license not found.
Register for a license at https://xcp.netapp.com
[user1@scspr2474004001 linux]$
----

.	Copy the license to `/home/user1/NetApp/xFiles/xcp/`:
+
----
[user1@scspr2474004001 linux]$ cp ~/license /home/user1/NetApp/xFiles/xcp/
[user1@scspr2474004001 linux]$
----

.	Verify that the license file was copied to `/home/user1/NetApp/xFiles/xcp/`:
+
----
[user1@scspr2474004001 xcp]$ ls -ltr
total 8
drwxrwxr-x 2 user1 user1  21 Sep 20 02:04 xcplogs
-rw-rw-r-- 1 user1 user1  71 Sep 20 02:04 xcp.ini
-rwxr-xr-x 1 user1 user1 352 Sep 20 02:10 license
[user1@scspr2474004001 xcp]$
----

.	Activate XCP:
+
----
[user1@scspr2474004001 linux]$ ./xcp activate
(c) yyyy NetApp, Inc.

XCP activated

[user1@scspr2474004001 linux]$
----

// 23 Oct 2023, OTHERDOC-34
//BURT 1391465 05/31/2021
//BURT 1450816, 2022-01-18
// 2023-04-26, OTHERDOC-7