---
sidebar: sidebar
permalink: xcp-nfs-reference-copy.html
keywords: netapp, xcp, reference, nfs, command, commands
summary: XCP NFS command reference
---

= copy
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The XCP NFS `copy` command scans and copies the entire source directory structure to a destination NFSv3 export.

The `copy` command requires having source and destination paths as variables. The scanned and copied files, throughput, speed, and elapsed time details are displayed at the end of the copy operation.

[NOTE]
====
* The runtime log file is located in `/opt/NetApp/xFiles/xcp/xcp.log` This path is configurable. Additional logging is located in the catalog after each command is run.
* If the source is a 7-Mode system, you can use a Snapshot copy as a source. For example: `<ip_address>:/vol/ex_s01/.snapshot/<snapshot_name>`
====

.Syntax
[source,cli]
xcp copy <source_nfs_export_path> <destination_nfs_export_path>

include::./_include/ref-example-nfs-copy.adoc[]

The following table lists the `copy` parameters and their description.

[cols=2*,options="header"]
|===
| Parameter
| Description
| <<copy -nonames>> | Excludes user and group names from file listings and reports.
| <<copy_match,copy -match <filter> >> | Only processes files and directories that match the filter.
| <<copy_md5, copy -md5 <string_expression> >> | Generates checksums on the files and saves the checksums when indexing (default: false). 
| <<copy_dircount,copy -dircount <n[k]> >> | Specifies the request size when reading directories.
| <<copy_edupe,copy -edupe>> | Includes the dedupe estimate in reports.
| <<copy_bs,copy -bs <n[k]> >> | Specifies the read/write block size (default: 64k).
| <<copy_parallel, copy -parallel <n> >> | Specifies the maximum number of concurrent batch processes (default: 7). 
| <<copy_preserve_atime,copy -preserve-atime>> | Restores all files to the last accessed date on the source.
| <<copy_s3_insecure,copy -s3.insecure>> | Provides the option to use HTTP instead of HTTPS for S3 bucket communication.
| <<copy_s3_endpoint,copy -s3.endpoint <s3_endpoint_url>>> | Overrides the default Amazon Web Services (AWS) endpoint URL with the specified URL for S3 bucket communication.
| <<copy_s3_profile,copy -s3.profile <profile_name>>> | Specifies a profile from the AWS credential file for S3 bucket communication.
| <<copy_s3_noverify,copy -s3.noverify>> | Overrides the default verification of SSL certification for S3 bucket communication.

|===

== copy -nonames

Use the `-nonames` parameter with the `copy` command to exclude user and group names from file listings or reports.

.Syntax

[source,cli]
xcp copy -nonames <source_ip_address_or_hostname>:/source_vol <destination_ip_address_or_hostname>:/dest_vol

include::./_include/ref-example-nfs-copy-nonames.adoc[]

[[copy_match]]
== copy -match <filter>

Use the `-match <filter>` parameter with the `copy` command to specify that only the files and directories that match a filter are processed.

.Syntax 

[source,cli]
xcp copy -match <filter> <source_ip_address_or_hostname>:/source_vol <destination_ip_address_or_hostname>:/dest_vol

include::./_include/ref-example-nfs-copy-match.adoc[]

[[copy_md5]]
== copy -md5 <string_expression>

Use the `-md5` parameter with the `copy` command to generate checksums for the file listings and save the checksums when indexing. The default value is set to false.

.Syntax

[source,cli]
xcp copy -md5 <source_ip_address_or_hostname>:/source_vol <destination_ip_address_or_hostname>:/dest_vol

include::./_include/ref-example-nfs-copy-md5.adoc[]

[[copy_dircount]]
== copy -dircount <n[k]>

Use the `-dircount <n[k]>` parameter with the `copy` command to specify the request size when reading directories. The default value is 64k.

.Syntax

[source,cli]
xcp copy -dircount <n[k]> <source_ip_address_or_hostname>:/source_vol <destination_ip_address_or_hostname>:/dest_vol

include::./_include/ref-example-nfs-copy-dircount.adoc[]

[[copy_edupe]]
== copy -edupe

Use the `-edupe` parameter with the `copy` command to include the deduplication estimate in reports.

.Syntax

[source,cli]
xcp copy -edupe <source_ip_address_or_hostname>:/source_vol <destination_ip_address_or_hostname>:/dest_vol

include::./_include/ref-example-nfs-copy-edupe.adoc[]

[[copy_bs]]
== copy -bs <n[k]>

Use the `-bs <n[k]>` parameter with the `copy` command to specify the read/write block size. The default block size is 64k. 

.Syntax

[source,cli]
xcp copy -bs <n[k]> <ip_address_or_hostname>:/source_vol <destination_ip_address_or_hostname>:/dest_vol

include::./_include/ref-example-nfs-copy-bs.adoc[]

[[copy_parallel]]
== copy -parallel <n> 

Use the `-parallel <n>` parameter with the `copy` command to specify the maximum number of concurrent batch processes. The default value is 7.

.Syntax

[source,cli]
xcp copy -parallel <n> <ip_address_or_hostname>:/source_vol destination_ip_address_or_hostname:/<dest_vol>

include::./_include/ref-example-nfs-copy-parallel.adoc[]

[[copy_preserve_atime]]
== copy -preserve-atime

Use the `-preserve-atime` parameter with the `copy` command to restore all files to the last accessed date on the source.

The `-preserve-atime` option resets the access time to the original value set before the XCP read operation.

.Syntax

[source,cli]
xcp copy -preserve-atime <source_ip_address_or_hostname>:/source_vol <destination_ip_address_or_hostname>:/dest_vol

include::./_include/ref-example-nfs-copy-preserveatime.adoc[]

[[copy_s3_insecure]]
== copy -s3.insecure

Use the `-s3.insecure` parameter with the `copy` command to use HTTP instead of HTTPS for S3 bucket communication.

.Syntax

[source,cli]
xcp copy -s3.insecure s3://<bucket_name>

include::./_include/ref-example-nfs-copy-s3-insecure.adoc[]

[[copy_s3_endpoint]]
== copy -s3.endpoint <s3_endpoint_url>

Use the `-s3.endpoint <s3_endpoint_url>` parameter with the `copy` command to override the default AWS endpoint URL with a specified URL for S3 bucket communication.

.Syntax

[source,cli]
xcp copy -s3.endpoint https://<endpoint_url>: s3://<bucket_name>

include::./_include/ref-example-nfs-copy-s3-endpoint.adoc[]

[[copy_s3_profile]]
== copy -s3.profile <name>

Use the `s3.profile` parameter with the `copy` command to specify a profile from the AWS credential file for S3 bucket communication.

.Syntax

[source,cli]
xcp copy -s3.profile <name> -s3.endpoint https://<endpoint_url>: s3://<bucket_name>

include::./_include/ref-example-nfs-copy-s3-endpoint.adoc[]

[[copy_s3_noverify]]
== copy -s3.noverify

Use the `-s3.noverify` parameter with the `copy` command to override the default verification of SSL certification for S3 bucket communication. 

.Syntax

[source,cli]
xcp copy -s3.noverify s3://<bucket_name>

include::./_include/ref-example-nfs-copy-s3-noverify.adoc[]

