---
sidebar: sidebar
permalink: xcp-prepare-linux-for-xcp-nfs.html
keywords: netapp, xcp, prepare, preparing, preparation, linux, nfs, configure, configuring, catalog, storage,
summary: Prepare Linux for XCP NFS
---

= Prepare Linux for XCP NFS
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
XCP NFS uses Linux client host systems to generate parallel I/O streams and fully use available network and storage performance.

=== Configure catalog

XCP saves operation reports and metadata in an NFSv3-accessible catalog directory. Provisioning the catalog is a one-time preinstallation task requiring the following:

*	A NetApp NFSv3 export for security and reliability.
*	At least ten disks or solid-state drives in the aggregate containing the export for performance.
*	Storage configured to allow root access to the catalog export for the IP addresses of all Linux clients used to run XCP (multiple XCP clients can share a catalog location).
*	Approximately 1 GB of space for every 10 million objects (directories plus files and hard links) to be indexed; each copy that can be resumed or synched and each offline-searchable scan requires an index.

NOTE: You should store XCP catalogs separately. They should not be located on either the source or the destination NFS export directory. XCP maintains metadata—reports in the catalog location specified during the initial setup. You must specify and update the location for storing the reports before you run any operation with XCP.

=== Configure storage

XCP NFS transitions and migrations have the following source and target storage requirements:

*	Source and target servers must have NFSv3 protocol service enabled. For NFSv4 ACL migration, you must enable NFSv4 protocol service and NFSv4 ACL on the destination server.
*	Source and target volumes must be exported with `root` access to the XCP Linux client host.

NOTE: Configure the source for NFSv3 and NFSv4 exports as read-only so administrators cannot accidentally modify it.

=== Configure a non-root user

Starting with XCP 1.8, you can perform data migration as a Linux non-root user, see link:xcp-install-xcp-nfs.html#install-xcp-for-a-non-root-user[Install XCP] and link:xcp-configure-the-ini-file-for-xcp-nfs.html#configure-the-ini-file-for-a-non-root-user[Configure XCP] for more information.

To perform data migration as a non-root user, you should have following configuration:

*	Read permission access to the source volume
*	Read/write permission access to the destination volume
*	Read/write permission access to the catalog volume
*	The source, destination, and catalog volumes should be mounted with version NFSv3 or NFSv4
