---
sidebar: sidebar
permalink: xcp-nfs-reference-delete.html
keywords: netapp, xcp, reference, nfs, command, commands
summary: XCP NFS command reference
---

= delete
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[lead]
The XCP NFS `delete` command deletes everything in a given path.

.Syntax
[source,cli]
xcp delete <NFS export path>

include::./_include/ref-example-nfs-delete.adoc[]

The following table lists the `delete` parameters and their description.

[cols=2*,options="header"]
|===
| Parameter
| Description
| <<nfs_delete_match, delete -match <filter>  >> | Only processes the files and directories that match the filter.
| <<nfs_delete_force, delete -force  >> | Deletes without confirmation.
| <<nfs_delete_removetopdir, delete -removetopdir >> | Removes the directory, including child directories.
| <<nfs_delete_exclude, delete -exclude <filter>  >> | Excludes the files and directories that match the filter. 
| <<nfs_delete_parallel, delete -parallel <n>  >> | Specifies the maximum concurrent batch processes (default: 7).
| <<nfs_delete_preserveatime, delete -preserve-atime >> | Preserves access time of the file or directory (default: false).
| <<nfs_delete_loglevel,delete -loglevel <name> >> | Sets the log level; available levels are INFO, DEBUG (default: INFO).
|  <<nfs_delete_s3_insecure,delete -s3.insecure>> | Provides the option to use HTTP instead of HTTPS for S3 bucket communication.
| <<nfs_delete_endpoint, delete -s3.endpoint <s3_endpoint_url> >> | Overrides the default Amazon Web Services (AWS) endpoint URL with the specified URL for S3 bucket communication.
| <<nfs_delete_s3_profile, delete -s3.profile <profile_name> >> | Specifies a profile from the AWS credential file for S3 bucket communication.
| <<nfs_delete_s3_noverify,delete -s3.noverify>> | Overrides the default verification of SSL certification for S3 bucket communication.
|===

[[nfs_delete_match]]
== delete -match <filter>

Use the `-match <filter>` parameter with the `delete` command to only process the files and directories that match the filter.

.Syntax

[source,cli]
xcp delete -match "fnm('XCP_copy_2023-04-25_05.51.28.315997')"
<ip_address>:/xcp_catalog

include::./_include/ref-example-nfs-delete-match.adoc[]

[[nfs_delete_force]]
== delete -force

Use the `-force` parameter with the `delete` command to delete without confirmation.

.Syntax

[source,cli]
xcp delete -force

include::./_include/ref-example-nfs-delete-force.adoc[]

[[nfs_delete_removetopdir]]
== delete -removetopdir

Use the `-removetopdir` parameter with the `delete` command to remove the directory, including child directories.

.Syntax

[source,cli]
xcp delete -force -loglevel DEBUG -removetopdir

include::./_include/ref-example-nfs-delete-removetopdir.adoc[]

[[nfs_delete_exclude]]
== delete -exclude <filter>

Use the `-exclude <filter>` parameter with the `delete` command to exclude the files and directories that match the filter. 

.Syntax

[source,cli]
xcp delete -force -exclude "fnm('preserve-atime5')" <ip_address>:/temp7/preserve-atime2/

include::./_include/ref-example-nfs-delete-exclude.adoc[]


[[nfs_delete_parallel]]
== delete -parallel <n>

Use the `-parallel <n>` parameter with the `delete` command to specify the maximum number of concurrent batch processes. The default value is 7.

.Syntax

[source,cli]
xcp delete -force -parallel 8 -match fnm('2023-04-
25_05.49.26.733160*')" <ip_address>:/xcp_catalog/

include::./_include/ref-example-nfs-delete-parallel.adoc[]

[[nfs_delete_preserveatime]]
== delete -preserve-atime 

Use the `-preserve-atime <preserve-atime>` parameter with the `delete` command to preserve the access time of a file or directory. The default value is false.

.Syntax

[source,cli]
xcp delete -force -preserve-atime <ip_address>:/temp7/user2/

include::./_include/ref-example-nfs-delete-preserveatime.adoc[]

[[nfs_delete_loglevel]]
== delete -loglevel <name>

Use the `-loglevel <name>` parameter with the `delete` command to set the log level; available levels are INFO, DEBUG. The default level is INFO.

.Syntax

[source,cli]
xcp delete -force -loglevel DEBUG -removetopdir <ip_address>:/temp7/user9

include::./_include/ref-example-nfs-delete-loglevel.adoc[]

[[nfs_delete_s3_insecure]]
== delete -s3.insecure

Use the `-s3.insecure` parameter with the `delete` command to use HTTP instead of HTTPS for S3 bucket communication.

.Syntax

[source,cli]
xcp delete -s3.insecure s3://bucket1

include::./_include/ref-example-nfs-delete-s3-insecure.adoc[]

[[nfs_delete_endpoint]]
== delete -s3.endpoint <s3_endpoint_url>

Use the `-s3.endpoint <s3_endpoint_url>` parameter with the `delete` command to override the default AWS endpoint URL with a specified URL for S3 bucket communication.

.Syntax

[source,cli]
xcp delete -s3.endpoint https://<endpoint_url>: s3://xcp-testing

include::./_include/ref-example-nfs-delete-s3-endpoint.adoc[]

[[nfs_delete_s3_profile]]
== delete -s3.profile <name>

Use the `s3.profile` parameter with the `delete` command to specify a profile from the AWS credential file for S3 bucket communication.

.Syntax

[source,cli]
xcp delete -s3.profile sg -s3.endpoint https://<endpoint_url>:
s3://bucket

include::./_include/ref-example-nfs-delete-s3-profile.adoc[]

[[nfs_delete_s3_noverify]]
== delete -s3.noverify

Use the `-s3.noverify` parameter with the `delete` command to override the default verification of SSL certification for S3 bucket communication. 

.Syntax

[source,cli]
xcp delete -s3.noverify s3://bucket

include::./_include/ref-example-nfs-delete-s3-noverify.adoc[]

