---
sidebar: sidebar
permalink: xcp-prepare-linux-for-xcp-nfs.html
keywords: netapp, xcp, prepare, preparing, preparation, linux, nfs, configure, configuring, catalog, storage,
summary: Prepare Linux for XCP NFS
---

= Prepare Linux for XCP NFS
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
XCP NFS uses Linux client host systems to generate parallel I/O streams and fully use available network and storage performance.

You can configure your setup for a root and a non-root user and then, depending on your setup, you can select either user.

== Configure catalog

XCP saves operation reports and metadata in an NFSv3-accessible catalog directory or on any POSIX path with the required permissions.

* Provisioning the catalog is a one-time pre-installation activity.
*	Approximately 1 GB of space is indexed for every 10 million objects (directories plus files and hard links); each copy that can be resumed or synched and each offline-searchable scan requires an index.
* To support performance, at least ten disks or SSDs are required in the aggregate containing the export directory.

NOTE: You must store XCP catalogs separately. They must not be located on either the source or the destination NFS export directory. XCP maintains the metadata, which are the reports in the catalog location specified during the initial setup. Before you run any operation using XCP, you must specify and update the location for storing the reports.

== Configure storage

XCP NFS transitions and migrations have the following source and target storage requirements:

*	Source and target servers must have the NFSv3 or NFS v4.0 protocol service enabled
** For NFSv4 ACL migration, you must enable NFSv4 protocol service and NFSv4 ACL on the destination server
* Source and target volumes must be exported with `root` access to the XCP Linux client host
* For NFSv4 ACL migration, NFSv4 requires that you use the encoding language UTF-8 for volumes that require ACL migration.

[NOTE]
====
* To prevent administrators accidentally modifying the source volume, you should configure the source volume for the NFSv3 and NFSv4 export directories as read-only.

* In ONTAP, you can use the diagnostic `-atime-update` option to preserve atime on source objects. This feature is only available in ONTAP and is helpful if you want to preserve atime in source objects while running XCP.

* In XCP, you can use the `-preserve-atime` option to preserve atime on source objects. This option is available to use with all commands that access source objects.
====

== Root user
A root user on a Linux machine has the permissions to mount the source, destination, and catalog volumes.

== Non-root user

A non-root user is required to have the following permissions on a mounted volume:

* Read permission access to the source volume
* Read/write permission access to the mounted destination volume
* Read/write permission access to the catalog volume

// BURT 1448943, 2022-02-01
// BURT 1455348, 2022-02-07
// BURT 1483365, 2022-06-29
