---
sidebar: sidebar
permalink: xcp-run-multiple-jobs-on-same-host.html
keywords: xcp, configure, nfs, posix, connector
summary: The POSIX connector gives XCP the capability to access any Linux-mounted file system, such as NFSv4, XFS, and Veritas.
---
= Run multiple XCP jobs on same XCP host
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Beginning with XCP 1.9.2, the "-minmem" feature supports running multiple XCP jobs and commands on a single host XCP host, provided the host has sufficient resources for each job. With the "-mimmem" feature, XCP uses minimal host memory to complete a job which creates the capacity to run additional jobs on the same host configuration.

== Minimum System Requirements
Yuo should allow up to 64GB of host memory and eight cores for medium to large migrations for each XCP job.

== Logging
By default, each XCP job is logged in a separate log file that is unique to the "JOB ID". This logging mechanism works well while running multiple jobs. Netapp does not recommended to use a single xcp.log(by changing the xcpLogConfig.Json) for logging while running multiple supported xcp jobs on the same host.

Supported commands:- 
scan, copy, resume, verify, isync, chmod, chown, delete

Unsupported commands:-
sync

Example:
User must run each job with “-minmem” option.
xcp copy -newid <id> -minmem src_server:/src_export dst_server:/dst_export
xcp resume [options] -id -minmem <id used for copy
xcp verify -minmem src_server:/src_export dst_server:/dst_export

HDFS path example:
xcp copy -minmem hdfs:///user/demo1/data file:///user/demo1/dest
xcp verify -minmem hdfs:///user/demo1/data file:///user/demo1/dest

POSIX path example:
xcp copy -minmem -newid <id> file:///mnt/source file:///mnt/dest
xcp verify -minmem file:///mnt/source file:///mnt/dest






// 2023 MAY 5, OTHERDOC-16
