---
sidebar: sidebar
permalink: xcp-using-file-analytics.html
keywords: netapp, xcp, plan, planning, data, migration, migrate, migrating, file, analytics
summary: Plan using File Analytics
---

= Plan using File Analytics
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Plan your data migration using File Analytics.

NOTE: XCP is a CLI, whereas File Analytics has a GUI.

*Overview*

XCP File Analytics uses the XCP scan API to collect data from NFS or SMB hosts. This data is then displayed on XCP File Analytics GUI. There are three main components involved in XCP File Analytics:

* XCP service
* File Analytics database
* File Analytics GUI to manage and view data

The deployment the method for XCP File Analytics components depends on the solution required:

*	Deploying XCP File Analytics solutions for NFS file systems:
** You can deploy the File Analytics GUI, database, and XCP service in the same Linux host.
*	Deploying XCP File Analytics solutions for SMB file systems:
You must deploy the File Analytics GUI and database in a Linux host and deploy the XCP service on a Windows host.
