---
sidebar: sidebar
permalink: xcp-nfs-reference-verify.html
keywords: netapp, xcp, reference, nfs, command, commands
summary: XCP NFS command reference
---

= verify
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The `verify` command uses full byte-by-byte data comparison between source and target directories after a copy operation without using a catalog index number. The command checks for modification times and other file or directory attributes, including permissions. The command also reads the files on both sides and compares the data.

.Syntax
[source,cli]
xcp verify <source NFS export path> <destination NFS exportpath>

include::./_include/ref-example-nfs-verify.adoc[]

The following table lists the `verify` parameters and their description.

[cols=2*,options="header"]
|===
| Parameter
| Description
| <<nfs_verify_stats_csv,verify -stats>> | Scans the source and target trees in parallel and compares tree statistics.
| <<nfs_verify_stats_csv,verify -csv>> | Scans the source and target trees in parallel and compares tree statistics.
| <<nfs_verify_nodata,verify -nodata>> | Does not check data.
| <<nfs_verify_noatts,verify -noattrs>>| Does not check attributes.
| <<nfs_verify_nomods,verify -nomods >>| Does not check file modification times.
| <<nfs_verify_mtimewindow,verify -mtimewindow <s> >> | Specifies the acceptable modification time difference for verification.
| <<nfs_verify_v_l, verify -v >> | Retrieves output formats to list any differences found.
| <<nfs_verify_v_l, verify -l >> | Retrieves output formats to list any differences found.
| <<nfs_verify_nonames, verify -nonames >> | Excludes user and group names for file listings or reports.
| <<nfs_verify_match, verify -match <filter> >> | Only processes files and directories that match the format.
| <<nfs_verify_bs,verify -bs <n[k]> >> | Specifies the read/write block size (default: 64k).
| <<nfs_verify_parallel, verify -parallel <n> >> | Specifies the maximum number of concurrent batch processes (default: 7).
| <<nfs_verify_dircount,verify -dircount <n[k]> >> | Specifies the request size when reading directories.
| <<nfs_verify_noid, verify -noId >> | Disables the creation of a default index (default: False).
| <<nfs_verify_preserveatime, verify -preserve-atime >> | Restores all files to the last accessed date on the source.
| <<nfs_verify_s3_insecure, verify -s3.insecure >> | Provides the option to use HTTP instead of HTTPS for S3 bucket communication. 
| <<nfs_verify_s3_endpoint, verify -s3.endpoint <s3_endpoint_url> >> | Overrides the default Amazon Web Services (AWS) endpoint URL with the specified URL for S3 bucket communication.
| <<nfs_verify_s3_profile, verify -s3.profile <profile_name> >> | Specifies a profile from the AWS credential file for S3 bucket communication.
| <<nfs_verify_s3_noverify, verify -s3.noverify>> | Overrides the default verification of SSL certification for S3 bucket communication.

|===

[[nfs_verify_stats_csv]]
== verify -stats and verify -csv

Use the `-stats` and `-csv` parameters with the `verify` command to scan the source and target trees in parallel and compare tree statistics.

.Syntax

[source,cli]
cp verify -stats <source_ip_address>:/source_vol <destination_ip_address>:/dest_vol

include::./_include/ref-example-nfs-verify-stats.adoc[]

.Syntax

[source,cli]
xcp verify -csv <source_ip_address>:/source_vol <destination_ip_address>:/dest_vol

include::./_include/ref-example-nfs-verify-csv.adoc[]

.Syntax 

[source,cli]
xcp verify -stats -csv <source_ip_address>:/source_vol <destination_ip_address>:/dest_vol

include::./_include/ref-example-nfs-verify-stats-csv.adoc[]

[[nfs_verify_nodata]]
== verify -nodata

Use the `-nodata` parameter with the `verify` command to specify not to check data. 

.Syntax

[source,cli]
xcp verify -nodata <source_ip_address>:/source_vol <destination_ip_address>:/dest_vol

include::./_include/ref-example-nfs-verify-nodata.adoc[]

[[nfs_verify_noatts]]
== verify -noattrs

Use the `-noattrs` parameter with the `verify` command to specify not to check attributes.

.Syntax

[source,cli]
xcp verify -noattrs <source_ip_address>:/source_vol <destination_ip_address>:/dest_vol

include::./_include/ref-example-nfs-verify-noattrs.adoc[]

[[nfs_verify_nomods]]
== verify -nomods

Use the `-nomods` parameter with the `verify` command to specify not to check file modification times.

.Syntax

[source,cli]
xcp verify -nomods <source_ip_address>:/source_vol <destination_ip_address>:/dest_vol

include::./_include/ref-example-nfs-verify-nomods.adoc[]

[[nfs_verify_mtimewindow]]
== verify -mtimewindow <s>

Use the `-mtimewindow <s>` parameter with the `verify` command to specify the acceptable modification time difference for verification.

.Syntax

[source,cli]
xcp verify -mtimewindow <s> <source_ip_address>:/source_vol <destination_ip_address>:/dest_vol

include::./_include/ref-example-nfs-verify-mtimewindow.adoc[]

[[nfs_verify_v_l]]
== verify -v and verify -l

Use the `-v` and `l` parameters with the `verify` command to retrieve output formats and list any differences found.

.Syntax

[source,cli]
xcp verify -v <source_ip_address>:/source_vol <destination_ip_address>:/dest_vol

include::./_include/ref-example-nfs-verify-v.adoc[]

.Syntax

[source,cli]
xcp verify -l <source_ip_address>:/source_vol <destination_ip_address>:/dest_vol

include::./_include/ref-example-nfs-verify-l.adoc[]

.Syntax

[source,cli]
xcp verify -v -l <source_ip_address>:/source_vol <destination_ip_address>:/dest_vol

include::./_include/ref-example-nfs-verify-v-l.adoc[]

[[nfs_verify_nonames]]
== verify -nonames

Use the `-nonames` parameter with the `verify` command to exclude user and group names for file listings or reports

.Syntax 

[source,cli]
xcp verify -nonames <source_ip_address>:/source_vol <destination_ip_address>:/dest_vol

include::./_include/ref-example-nfs-verify-nonames.adoc[]

[[nfs_verify_match]]
== verify -match <filter>

Use the `-match <filter>` parameter with the `verify` command to only process the files and directories that match the filter.

.Syntax 

[source,cli]
xcp verify -match bin <source_ip_address>:/source_vol <destination_ip_address>:/dest_vol

include::./_include/ref-example-nfs-verify-match.adoc[]

[[nfs_verify_bs]]
== verify -bs <n>

Use the `-bs <n>` parameter with the `verify` command to specify the read/write block size. The default value is 64k.

.Syntax 

[source,cli]
xcp verify -bs 32k  <source_ip_address>:/source_vol <destination_ip_address>:/dest_vol

include::./_include/ref-example-nfs-verify-bs.adoc[]

[[nfs_verify_parallel]]
== verify -parallel <n>

Use the `-parallel <n>` parameter with the `verify` command to specify the maximum number of concurrent batch processes.

.Syntax

[source,cli]
xcp verify -parallel <source_ip_address>:/source_vol <destination_ip_address>:/dest_vol

include::./_include/ref-example-nfs-verify-parallel.adoc[]

[[nfs_verify_dircount]]
== verify -dircount <n[k]>

Use the `-dircount <n[k]>` parameter with the `verify` command to specify the request size when reading directories. The default value is 64k. 
 
.Syntax

[source,cli] 
xcp verify -dircount <n[k]> <source_ip_address>:/source_vol <destination_ip_address>:/dest_vol

include::./_include/ref-example-nfs-verify-dircount.adoc[]

[[nfs_verify_noid]]
== verify -noId

Use the `-noId` parameter with the `verify` command to disable the creation of a default index. The default value is false.

.Syntax

[source,cli]
xcp verify -noId <source_ip_address>:/source_vol <destination_ip_address>:/dest_vol

include::./_include/ref-example-nfs-verify-noid.adoc[]

[[nfs_verify_preserveatime]]
== verify -preserve-atime

Use the `-preserve-atime` parameter with the `verify` command to restore all files to the last accessed date on the source. The `-preserve-atime` parameter resets the access time to the original value set before the XCP read operation.

.Syntax

[source,cli]
xcp verify -preserve-atime <source_ip_address>:/source_vol <destination_ip_address>:/dest_vol

include::./_include/ref-example-nfs-verify-preserveatime.adoc[]

[[nfs_verify_s3_insecure]]
== verify -s3.insecure

Use the `-s3.insecure` parameter with the `verify` command to use HTTP instead of HTTPS for S3 bucket communication.

.Syntax

[source,cli]
xcp verify -s3.insecure hdfs:///user/test s3://<bucket_name>

include::./_include/ref-example-nfs-verify-s3-insecure.adoc[]

[[nfs_verify_s3_endpoint]]
== verify -s3.endpoint <s3_endpoint_url>

Use the `-s3.endpoint <s3_endpoint_url>` parameter with the `verify` command to override the default AWS endpoint URL with a specified URL for S3 bucket communication.

.Syntax

[source,cli]
xcp verify -s3.endpoint https://<endpoint_url>: s3://<bucket_name>

include::./_include/ref-example-nfs-verify-s3-endpoint.adoc[]

[[nfs_verify_s3_profile]]
== verify -s3.profile <name>

Use the `s3.profile` parameter with the `verify` command to specify a profile from the AWS credential file for S3 bucket communication.

.Syntax

[source,cli]
xcp verify -s3.profile <name> -s3.endpoint https://<endpoint_url>: s3://<bucket_name>

include::./_include/ref-example-nfs-verify-s3-profile.adoc[]

[[nfs_verify_s3_noverify]]
== verify -s3.noverify

Use the `-s3.noverify` parameter with the `verify` command to override the default verification of SSL certification for S3 bucket communication. 

.Syntax

[source,cli]
xcp verify -s3.noverify s3://<bucket_name>

include::./_include/ref-example-nfs-verify-s3-noverify.adoc[]

