---
sidebar: sidebar
permalink: xcp-troubleshoot-xcp-file-analytics-errors.html
keywords: netapp, xcp, troubleshoot, troubleshooting, errors, file, anyalytics
summary: Troubleshooting XCP File Analytics errors
---

= Troubleshoot XCP File Analytics errors
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Review the solutions to troubleshoot your issue.

[cols="40,60"options="header"]
|===
|Issue |Solution

|PostgreSQL service failed
a|Run configure again and select the installation option. If the previous installation was successful, you can select the repair option. If you are still getting the error, try manual steps as follows:

. Restart the PostgreSQL service:
+
`sudo systemctl restart postgresql.service`
. Check the service status:
+
`sudo systemctl status postgresql.service \| grep Active`

|HTTPD service failed
a|Run configure again and select the installation option. If the previous installation was successful, you can select the repair option. If you are still getting the error, try manual steps as follows:

.	Restart the HTTPD services:
+
`sudo systemctl restart httpd`
.	Check the HTTPD service status:
+
`sudo systemctl status httpd \| grep Active`

|Not able to open login page after successful install
|Verify that your system can ping the Linux machine where XCP File Analytics is installed and HTTPD is running. If the services are not running, run `configure` and choose the repair option.

Verify that you are using a supported browser version. See the link:https://mysupport.netapp.com/matrix/[IMT^].
|User login failed
a|*	Verify that you are using a supported browser version. See the link:https://mysupport.netapp.com/matrix/[IMT^].
*	Verify that the user is “admin” and the password is correct.
*	Verify that the XCP service is running by issuing `xcp service status`.
*	Verify that port  5030 is open on Linux. Open the application at *https:// <linux ip> :5030/api/xcp*, and confirm that the messagereads msg: `Missing Authorization Header`.
*	Check whether the `xcp.ini` file is present in the `/opt/NetApp/xFiles/xcp/` location. To reset the `xcp.ini` file, run the configuration script and select the *Repair* option. Next, select the menu option to *rebuild xcp.ini file*.
* Manually run the `xcp --listen` command on the CLI and try logging in. If you do not receive a request on the server, re-check the installation and the ports used for communication with the server.  After you verify that the installation is correct, run the `service xcp start` command to restart the service.
|XCP GUI is not showing updated pages
|Clear the cache and try again
|XCP service is not starting
|To run the `xcp` service, use the `sudo systemctl start xcp` command. Alternatively, run the configuration script and select the *Repair* option to start the services that are stopped.
|Failed to scan file share
|File share/volume might not be readable. Check manually whether the file share is accessible/readable by running the `xcp show` command.
Also, check if the `xcp.ini` file is deleted. If it is deleted, rebuild the `xcp.ini` file by using the configure.sh script repair option.
|Could not load file servers
|Try a page refresh. If the problem persists, manually run the `xcp show` command on the prompt and check whether you can scan the file server. If successful, raise a ticket with NetApp customer support. If unsuccessful, check if the file server is active by performing a manual check.

Check whether the `xcp.ini` file and license files are in the correct location. To reset the `xcp.ini` file, run the configuration script and select the *Repair* option. Next, select the menu option to *rebuild xcp.ini file.*

Check the `xcpfalogs` logs to see if the license needs renewal.
|XCP File Analytics page is not displayed after system reboot
|XCP services might be down. Run the configuration script and select the option to *Repair*. This will restart all the services that are stopped.
|The total space for an exported file system on a given file server might show more space compared to the allocated physical storage.
|This can happen when there are qtree level exports inside the volume.
For example, if the volume size that is exported as `/vol1` is 10 GB  and there is a qtree inside the volume `/vol1/qtree1`, then the `xcp show` command will show the `vol1` size as `10 GB` and the `qtree1` size as `10 GB`. XCP File Analytics sums the space of both exports and gives the total space, in this case, `20 GB`. It does not understand that `qtree1` is a logical space.
|===

// BURT 1391465 06/29/2021
// 2021-Nov-08, BURT 1423222
