---
sidebar: sidebar
permalink: xcp-run-multiple-jobs-on-same-host.html
keywords: xcp, configure, nfs, posix, connector
summary: The POSIX connector gives XCP the capability to access any Linux-mounted file system, such as NFSv4, XFS, and Veritas.
---
= Run multiple XCP jobs on the same XCP host
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Beginning with XCP 1.9.2, you can run multiple XCP jobs or commands on a single XCP host, provided that the host has sufficient resources for each job. When you run a command that supports the multiple jobs, XCP uses minimal host memory to complete the job which creates the capacity to run additional jobs on the same host configuration.

== Minimum system requirements
For each XCP job, you should allow up to 64GB of host memory and eight cores for medium to large migrations. 

NOTE: Running multiple XCP jobs on the same host is not supported for SMB data migration. 

== Logging
By default, each XCP job is logged in a separate log file that is unique to the job ID. This logging mechanism works well when running multiple jobs on the same individual host. NetApp does not recommend changing the `xcpLogConfig.Json` file to use a single `xcp.log` file to log multiple XCP jobs running in parallel on the same host.

== Supported commands
Running multiple XCP jobs on the same host is supported with the following XCP commands:

* `scan`
* `copy`
* `resume`
* `verify` 
* `isync`
* `chmod`
* `chown`
* `delete`

== Unsupported commands
Running multiple XCP jobs on the same host is not supported with the `sync` command.


// 2023 MAY 5, OTHERDOC-16
