---
sidebar: sidebar
permalink: xcp-supported-features.html
keywords: netapp, xcp, about, features, unsupported, supported, configuration
summary: NetApp XCP allows for scalable and high-performance data migrations
---
= Supported workflows and configurations
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The following workflows and configurations are supported by XCP.

== Supported workflows in XCP
Starting from XCP 1.7, when a source is active, that is you are actively using the source volume and changing data on the source, you can migrate the source data to the destination.  During the migration, XCP makes runtime calls to detect the state of the files which are being copied to decide whether or not to copy the data to the destination. As a result, because you are continuously modifying the data, XCP might not copy all the data from the source to the destination. Starting from XCP 1.7, the data that is not copied to the destination will get copied in the next incremental sync operation if XCP does not detect any more anomalies.

For XCP 1.6.3 and earlier, XCP provides support for the following migration workflows:

* *Snap based migration:* Enables you to create a baseline snapshot to copy data and later use incremental snapshot to sync the data, followed by cutover snapshot. In each case, you can run verify the operation to check the integrity of the data at any point in migration.
* *Non-snapshot-based migration:* Enables you to do baseline data directly from the volume which ensures you stop all I/O operations for the source volume and continues this for the incremental sync operation until you do the cutover. For this case workflow, XCP cannot detect if you have not followed proper procedure.
* *Mix of snapshot and read-only source volume:* When performing out the migration, you can switch from a read-only volume to the snapshot until you do the cutover.

Starting form XCP 1.7, the following migration workflow is also supported:

* *Live non-snapshot-based migration:*
+
The live non-snapshot-based migration workflow enables you to perform the following functions:

** You can find out if a source is live.
** You can use XCP and perform a baseline copy. However, if you also run verify the operation might fail. Wait until after a successful baseline copy before you perform the next step.
** You can use XCP to perform an incremental sync operation. However, if you also run verify the operation might fail. You should perform an incremental sync operation until your changes are minimal or you have identified time for a cutover.
** In the cutover window, stop all I/O operations for the source volume by using the following steps:
+
. Run the final sync operation.
. Run the verify option.

NOTE: In all cases, to enable you to complete a successful XCP migration operation, you should rely on the XCP STATUS messages. If you get any failure messages, you can contact customer support or you can refer to link:xcp-troubleshoot-migrattion-wf.html[Troubleshoot XCP migration workflows] for more information and possible solutions.

== Visible changes for a live source
You can check if the source is live after you perform an XCP migration command by checking the console messages. On the console, additional messages are only visible during a copy or sync operation when the source data is changing for append and deletion operations. These messages only appear when XCP detects if a source is live during a migration, otherwise these messages are not displayed.

The is an example of a console message during a copy or sync operation:

----
Unreadable dirs : 0, Unreadable files : 4, Files modified while reading : 4, Total hardlinks of skipped files : 6


Skipped summary : 4 files were being modified while reading. Total hardlinks of skipped files were 6.


Reason for skipping :

* Files were modified/deleted while sync was in progress.

Corrective action : Since source data was modified during sync operation, run sync command for incremental changes.

Please check xcp.log file to get details on skipped files.
----

The number of files, directories, and links which are skipped during a migration are listed on the console and the reason for skipping this data is printed. This information is only available to the end user and always appears for a live source migration when you are modifying files and directories during the migration because XCP cannot copy and sync the data. This information tells you what files have not been copied, but you cannot use it to selectively copy these files in the next incremental sync operation.

== Supported configurations

All the XCP supported configurations such as hosts, ONTAP versions, and supported browsers, are listed in the link:https://mysupport.netapp.com/matrix/[Interoperability Matrix Tool (IMT)^].

//BURT 1391465 05/31/2021
