---
sidebar: sidebar
permalink: xcp-migrate-data.html
keywords: netapp, xcp, migrate, data, nfs, smb, copy, resume, sync, verify
summary: Migrate data
---

= Migrate data
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== Migrate NFS data

After planning the migration with the show and scan commands, you can migrate data.

==== Copy

The `copy` command scans and copies the entire source directory structure to a destination NFSv3 export. The `copy` command requires having source and destination paths as variables. The scanned and copied files, throughput/speed, and elapsed time details are displayed at the end of the copy operation

*Example:*

----
xcp copy -newid <id> src_server:/src_export dst_server:/dst_export
----

See `xcp help copy` for more details.

==== Resume:

The `resume` command restarts a previously interrupted copy operation by specifying the catalog index name or number. The catalog index name or number of the previous copy operation is stored on the `<catalog path>:/catalog/indexes` directory.

*Example:*

----
xcp resume [options] -id <id used for copy>
----

See `xcp help resume` for more details.

==== Sync

The `sync` command scans for changes and modifications performed on a source NFS directory using a catalog index tag name or the number of a previous copy operation. Source incremental changes are copied and applied to the target directory. The old catalog index numbers are replaced with a new one [.underline]#after the sync operation#.

*Example:*
----
xcp sync [options] -id <id used for copy>
----

See `xcp help sync` for more details.

==== Verify
The `verify` command uses a full byte-by-byte data comparison between source and target directories after the copy operation without using a catalog index number. The command checks for modification times and other file or directory attributes, including permissions. The command also reads the files on both sides and compares the data.

*Example:*

`xcp verify [options]``
----
xcp verify [options] src_server:/src_export dst_server:/dst_export
----

See `xcp help verify` for more details.

== Migrate SMB data

After planning the migration with the show and scan commands, you can migrate data.

==== Copy
The `copy` command scans and copies the entire source directory structure to a destination SMB share. The `copy` command requires having source and destination paths as variables. The scanned and copied files, throughput/speed, and elapsed time details are printed to the console once every five seconds.

*Example:*

----
C:\xcp>xcp copy \\<source SMB share> \\<destination SMB share>
----

See `xcp help copy` for more details.

==== Sync

The `sync` command scans for changes and modifications in the source and target shares in parallel, and applies the appropriate actions (remove, modify, rename, and so on) to the target to make sure that the target is identical to the source.

The sync command compares data content, time stamps, file attributes, ownership, and security information.

*Example:*

----
C:\xcp>xcp sync \\<source SMB share> \\<destination SMB share>
----

See `xcp help sync` for more details.

==== Verify

The `verify` command reads both source and target shares and compares them, providing information about what is different. You can use the command on any source and destination, regardless of the tool used to perform the copy or sync.

*Example:*

----
C:\xcp>xcp verify \\<source SMB share> \\<destination SMB share>
----

See `xcp help verify` for more details.
