---
sidebar: sidebar
permalink: xcp-nfs-reference-scan.html
keywords: netapp, xcp, reference, nfs, command, commands
summary: XCP NFS command reference
---

= scan
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[lead]
The XCP NFS `scan` command recursively scans the entire source NFSv3 exported paths and returns file structure statistics. 

NetApp recommends that you put the source NFS export mounts in read-only mode during the scan operation.

.Syntax
[source,cli]
xcp scan <source_nfs_export_path>

.Show example
[%collapsible]
====
<enter_example>
====

== Parameters

The following table lists the `scan` parameters and their description.

[cols=2*,options="header"]
|===
| Parameter
| Description
| <<scan -l and scan -q,scan -l>> | Retrieves file listing output formats.
| <<scan -l and scan -q,scan -q>> | Retrieves file listing output formats.
| `scan -stats` | Retrieves tree statistic report formats.
| `scan -csv` | Retrieves tree statistic report formats.
| `scan -html`| Retrieves tree statistic report formats.
| <<scan -nonames>> | Excludes user and group names for file listings and reports.
| `scan -newid <name>` | Specifies the catalog name for a new index.
| `scan -id <catalog_name>` | Specifies the catalog name of a previous copy or scan index.
| `scan -match <filter>` | Only processes files and directories that match the filter.
| `scan -fmt <string_expression>` | Only processes files and directories that match the format.
| `scan -du` | Summarizes the space usage of each directory, including subdirectories.
| `scan -md5 <string_expression>` | Generates checksums on the files and saves the checksums when indexing (default: false). 
| `scan -depth <n>` | Limits the search depth.
| `scan -dircount <n[k]>` | Specifies the request size when reading directories.
| `scan -edupe` | Includes the dedupe estimate in reports.
| `scan -bs <n[k]>` | Specifies the read/write block size for scans that read data using `-md5` or `-edupe` (default: 64k).
| `scan -parallel <n>` | Specifies the maximum number of concurrent batch processes (default: 7). 
| `scan -noId` | Disables the creation of a default index (default: false).
| `scan -subdir-names` | Retrieves the names of the top-level subdirectories in a directory.
| `scan -acl4` | Processes NFSv4 access control lists (ACLs).
| `scan -preserve-atime` | Restores all files to the last accessed date on the source.
| `scan -s3.insecure` | Provides the option to use HTTP instead of HTTPS for S3 bucket communication.
| `scan -s3.endpoint <s3_endpoint_url>` | Overrides the default Amazon Web Services (AWS) endpoint URL with the specified URL for S3 bucket communication.
| `scan -s3.profile <profile_name>` | Specifies a profile from the AWS credential file for S3 bucket communication.
| `scan -s3.noverify` | Overrides the default verification of SSL certification for S3 bucket communication.

|===

== scan -l and scan -q

Retrieve file listing output formats.

.Syntax

[source,cli]
xcp scan -l <ip_address_or_hostname>:/source_vol

.Show example
[%collapsible]
====
<enter_example>
====

.Syntax

[source,cli]
xcp scan -q <ip_address_or_hostname>:/source_vol

.Show example
[%collapsible]
====
<enter_example>
====

== scan -stats, scan -csv, and scan -html

Retrieve tree statistic report formats.

NOTE: XCP reports (.csv, .html) are saved in the catalog location specified in the `xcp.ini` file. The files are stored in the `<catalog path>/catalog/indexes/1/reports` folder. You can view sample reports in the appendix.

.Syntax

[source,cli]
xcp scan -stats <ip_address>:/source_vol

.Show example
[%collapsible]
====
<enter_example>
====

.Syntax

[source,cli]
xcp scan -csv <ip_address_or_hostname>:/source_vol

.Show example
[%collapsible]
====
<enter_example>
====

.Syntax

[source,cli]
xcp scan -html <ip_address_or_hostname>:/source_vol

.Show example
[%collapsible]
====
<enter_example>
====

== scan -nonames

Exclude user and group names for file listings or reports.

NOTE: When used with the `scan` command, the `-nonames` parameter only applies to file listings returned using the `-l` option.

.Syntax

[source,cli]
xcp scan -nonames <ip_address_or_hostname>:/source_vol

.Show example
[%collapsible]
====
<enter_example>
====

== scan -newid <name>

Specify the catalog name for a new index when running a scan.

.Syntax

[source,cli]
xcp scan -newid <name> <ip_address_or_hostname>:/source_vol

.Show example
[%collapsible]
====
<enter_example>
====

== scan -id

Specify the catalog name of previous copy or scan index.

.Syntax

[source,cli]
xcp scan -id <catalog_name> 

.Show example
[%collapsible]
====
<enter_example>
====


== scan -match <filter>

Specify that only the files and directories that match a filter are processed.

.Syntax 

[source,cli]
xcp scan -match <filter> <ip_address_or_hostname>:/source_vol

.Show example
[%collapsible]
====
<enter_example>
====

== scan -fmt

Specify that only files and directories that match the specified format are returned.

.Syntax

[source,cli]
xcp scan -fmt <string_expression> <ip_address_or_hostname>:/source_vol

.Show example
[%collapsible]
====
<enter_example>
====

== scan -du

Summarize the space usage of each directory, including subdirectories.

.Syntax

[source,cli]
xcp scan -du <ip_address_or_hostname>:/source_vol

.Show example
[%collapsible]
====
<enter_example>
====

== scan -md5

Generate checksums for the file listings and save the checksums when indexing. The default value is set to false.

NOTE: The checksums are not used for file verification; they are only used for file listings during scan operations.

.Syntax

[source,cli]
xcp scan -md5 <ip_address_or_hostname>:/source_vol

.Show example
[%collapsible]
====
<enter_example>
====

== scan -depth <n>

Limit the search depth of a scan. The `-depth <n>` parameter specifies the depth into the subdirectories that XCP can scan files. For example, if the number 2 is specified, XCP will only scan the first two subdirectory levels.

.Syntax

[source,cli]
xcp scan -depth <n> <ip_address_or_hostname>:/source_vol

.Show example
[%collapsible]
====
<enter_example>
====

== scan -dircount <n[k]>

Specify the request size when reading directories in a scan. The default value is 64k.

.Syntax

[source,cli]
xcp scan -dircount <n[k]> <ip_address_or_hostname>:/source_vol

.Show example
[%collapsible]
====
<enter_example>
====

== scan -edupe

Include the deduplication estimate in reports.

.Syntax

[source,cli]
xcp scan -edupe <ip_address_or_hostname>:/source_vol

.Show example
[%collapsible]
====
<enter_example>
====

== scan -bs <n[k]>

Specify the read/write block size for scans that read data using the `-md5` or `-edupe` parameters. The default block size is 64k. 

.Syntax

[source,cli]
xcp scan -bs <n[k]> <ip_address_or_hostname>:/source_vol

.Show example
[%collapsible]
====
<enter_example>
====

== scan -parallel <n> 

Specify the maximum number of concurrent patch processes. The default value is 7.

.Syntax

[source,cli]
xcp scan -parallel <n> <ip_address_or_hostname>:/source_vol

.Show example
[%collapsible]
====
<enter_example>
====

== scan -noId

Disable the creation of a default index by using the `-noId` parameter. The default value is false.

.Syntax

[source,cli]
xcp scan -noId <ip_address_or_hostname>:/source_vol

.Show example
[%collapsible]
====
<enter_example>
====

== scan -subdir-names

Retrieve the names of the top-level subdirectories in a directory. 

.Syntax

[source,cli]
xcp scan -subdir-names <ip_address_or_hostname>:/source_vol

.Show example
[%collapsible]
====
<enter_example>
====

== scan -acl4

Process NFSv4 ACLs by using the `-acl4` parameter. 

.Syntax

[source,cli]
xcp scan -acl4 <ip_address_or_hostname>:/source_vol

.Show example
[%collapsible]
====
<enter_example>
====

== scan -preserve-atime 

Restore all files to the last accessed date on the source. 

When an NFS share is scanned, the access time is modified on the files if the storage system is configured to modify access time on read. XCP does not directly change the access time, XCP reads the files one by one and this triggers an update to the access time. The `-preserve-atime` option resets the access time to the original value set before the XCP read operation.

.Syntax

[source,cli]
xcp scan -preserve-atime <ip_address_or_hostname>:/source_vol

.Show example
[%collapsible]
====
<enter_example>
====

== scan -s3.insecure

Use HTTP instead of HTTPS for S3 bucket communication.

.Syntax

[source,cli]
xcp scan -s3.insecure s3://<bucket_name>

.Show example
[%collapsible]
====
<enter_example>
====

== scan -s3.endpoint

Override the default AWS endpoint URL with a specified URL for S3 bucket communication.

.Syntax

[source,cli]
xcp scan -s3.endpoint https://<endpoint_url>: s3://<bucket_name>

.Show example
[%collapsible]
====
<enter_example>
====

== scan -s3.profile <name>

Specify a profile from the AWS credential file for S3 bucket communication.

.Syntax

[source,cli]
xcp scan -s3.profile <name> -s3.endpoint https://<endpoint_url>: s3://<bucket_name>

.Show example
[%collapsible]
====
<enter_example>
====

== scan -s3.noverify

Override the default verification of SSL certification for S3 bucket communication. 

.Syntax

[source,cli]
xcp scan -s3.noverify s3://<bucket_name>

.Show example
[%collapsible]
====
<enter_example>
====

