---
sidebar: sidebar
permalink: xcp-nfs-ref-scan-descriptions.html
keywords: netapp, xcp, reference, nfs, command, commands
summary: XCP NFS command reference
---

= scan command parameters
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[lead]
This command reference document provides the parameters, descriptions, and examples for the XCP NFS `scan` command.  

== Retrieve file listing output formats

You can retrieve file listing output formats by using the following parameters: 

* `scan -l`
* `scan -q`

.Syntax

[source,cli]
 ./xcp scan -l <ip_address_or_hostname>:/<source_vol>

.Example 

----
<enter_example>
----

.Syntax

[source,cli]
 ./xcp scan -q <ip_address_or_hostname>:/<source_vol>

.Example

----
<enter_example>
----

== Retrieve tree statistic report formats

You can retrieve tree statistic report formats by using the following parameters:

* `scan -stats`
* `scan -csv` 
* `scan -html` 

NOTE: XCP reports (.csv, .html) are saved in the catalog location specified in the `xcp.ini` file. The files are stored in the `<catalog path>/catalog/indexes/1/reports` folder. You can view sample reports in the appendix.

.Syntax

[source,cli]
 ./xcp scan -stats <ip_address>:/<source_vol>

.Example 

----
<enter_example>
----

.Syntax

[source,cli]
 ./xcp scan -csv <ip_address_or_hostname>:/<source_vol>

.Example

----
<enter_example>
----

.Syntax

[source,cli]
 ./xcp scan -html <ip_address_or_hostname>:/<source_vol>

.Example

----
<enter_example>
----

== Exclude user and group names for file listings or reports

You can exclude user and group names for file listings or reports by using the `-nonames` parameter.

NOTE: The `-nonames` parameter only applies to file listings returned using the `-l` option with the `scan` command.

.Syntax

[source,cli]
  ./xcp scan -nonames <ip_address_or_hostname>:/<source_vol>

.Example

----
<enter_example>
----

== Specify the catalog name for a new index

You can specify the catalog name for a new index when running a scan by using the `-newid <name>` parameter. 

.Syntax

[source,cli]
  ./xcp scan -newid <name> <ip_address_or_hostname>:/<source_vol>

.Example

----
<enter_example>
----

== Specify the catalog name of a previous copy or scan index

You can specify the catalog name of previous copy or scan index by using the `-id <name>` parameter.

.Syntax

[source,cli]
  ./xcp scan -id <name> 

.Example

----
<enter_example>
----


== Only process the files and directories that match the filter

You can specify that only the files and directories that match a filter are processed by using the `-match <filter>` parameter.

[source,cli]
  ./xcp scan -match <filter> <ip_address_or_hostname>:/<source_vol>

.Example

----
<enter_example>
----

== Only process the files and directories that match the format

You can specify that only files and directories that match the specified format are returned by using the `-fmt` parameter.

[source,cli]
  ./xcp scan -fmt <string_expression> <ip_address_or_hostname>:/<source_vol>

.Example

----
<enter_example>
----

== Summarize the space usage of each directory, including subdirectories

You can summarize the space usage of each directory, including subdirectories, by using the `-du` parameter.

.Syntax

[source,cli]
 ./xcp scan -du <ip_address_or_hostname>:/<source_vol>

.Example

----
<enter_example>
----

== Generate checksums for file listings and save the checksums when indexing

You can generate checksums for the file listings and save the checksums when indexing by using the `-md5` parameter. 

The default value is false.

NOTE: The checksums are not used for file verification; they are only used for file listings during scan operations.

.Syntax

[source,cli]
  ./xcp scan -md5 <ip_address_or_hostname>:/<source_vol>

.Example

----
<enter_example>
----

== Limit the search depth

You can limit the search depth of a scan by using the `` parameter. The `-depth <n>` parameter specifies how deeply into the subdirectories the XCP scan is run.

.Syntax

[source,cli]
 ./xcp scan -depth <n> <ip_address_or_hostname>:/<source_vol>

.Example

----
<enter_example>
----

== 

