---
sidebar: sidebar
permalink: xcp-nfs-reference-scan.html
keywords: netapp, xcp, reference, nfs, command, commands
summary: XCP NFS command reference
---

= scan
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The XCP NFS `scan` command recursively scans the entire source NFSv3 exported paths and returns file structure statistics. 

NetApp recommends that you put the source NFS export mounts in read-only mode during the scan operation.

.Syntax
[source,cli]
xcp scan <source_nfs_export_path>

include::./_include/ref-example-nfs-scan.adoc[]

The following table lists the `scan` parameters and their description.

[cols=2*,options="header"]
|===
| Parameter
| Description
| <<scan_l,scan -l>> | Lists files in the long listing output format.
| <<scan_q,scan -q>> | Shows the number of files scanned.
| <<nfs_scan_stats_csv_html,scan -stats>> | Lists files in the tree statistic report format.
| <<nfs_scan_stats_csv_html,scan -csv>>| Lists files in the tree statistic CSV report format.
| <<nfs_scan_stats_csv_html,scan -html>>| Lists files in the tree statistic HTML report format.
| <<scan -nonames>> | Excludes user and group names from file listings and reports.
| <<nfs_scan_newid, scan -newid <name> >> | Specifies the catalog name for a new index.
| <<nfs_scan_id, scan -id <catalog_name> >> | Specifies the catalog name of a previous copy or scan index.
| <<nfs_scan_match, scan -match <filter> >> | Only processes files and directories that match the filter.
| <<nfs_scan_fmt, scan -fmt <string_expression> >> | Only processes files and directories that match the format.
| <<nfs_scan_du,scan -du>> | Summarizes the space usage of each directory, including subdirectories.
| <<nfs_scan_md5, scan -md5 <string_expression> >> | Generates checksums on the files and saves the checksums when indexing (default: false). 
| <<nfs_scan_depth,scan -depth <n> >> | Limits the search depth.
| <<nfs_scan_dircount, scan -dircount <n[k]> >> | Specifies the request size when reading directories.
| <<nfs_scan_edupe, scan -edupe>> | Includes the dedupe estimate in reports.
| <<nfs_scan_bs, scan -bs <n[k]> >> | Specifies the read/write block size for scans that read data using `-md5` or `-edupe` (default: 64k).
| <<nfs_scan_parallel, scan -parallel <n> >> | Specifies the maximum number of concurrent batch processes (default: 7). 
| <<nfs_scan_noid,scan -noId >>| Disables the creation of a default index (default: false).
| <<nfs_scan_subdir, scan -subdir-names>> | Retrieves the names of the top-level subdirectories in a directory.
| <<scan -preserve-atime>> | Restores all files to the last accessed date on the source.
| <<scan -s3.insecure>> | Provides the option to use HTTP instead of HTTPS for S3 bucket communication.
| <<nfs_scan_endpoint, scan -s3.endpoint <s3_endpoint_url> >> | Overrides the default Amazon Web Services (AWS) endpoint URL with the specified URL for S3 bucket communication.
| <<nfs_scan_s3_profile, scan -s3.profile <profile_name> >> | Specifies a profile from the AWS credential file for S3 bucket communication.
| <<scan -s3.noverify>> | Overrides the default verification of SSL certification for S3 bucket communication.

|===

[[scan_l]]
== scan -l

Use the `-l` parameter with the `scan` command to list files in the long listing output format.

.Syntax

[source,cli]
xcp scan -l <ip_address_or_hostname>:/source_vol

include::./_include/ref-example-nfs-scan-l.adoc[]

[[scan_q]]
== scan -q

Use the `-q` parameter with the `scan` command to show the number of files scanned.

.Syntax

[source,cli]
xcp scan -q <ip_address_or_hostname>:/source_vol

include::./_include/ref-example-nfs-scan-q.adoc[]

[[nfs_scan_stats_csv_html]]
== scan -stats, scan -csv, and scan -html

Use the `-stats`, `-csv`, and `-html` parameters with the `scan` command to list files in the tree statistic report format.

NOTE: XCP reports (.csv, .html) are saved in the catalog location specified in the `xcp.ini` file. The files are stored in the `<catalog path>/catalog/indexes/1/reports` folder. You can view sample reports in the appendix.

.Syntax

[source,cli]
xcp scan -stats <ip_address>:/source_vol

include::./_include/ref-example-nfs-scan-stats.adoc[]

.Syntax

[source,cli]
xcp scan -csv <ip_address_or_hostname>:/source_vol

include::./_include/ref-example-nfs-scan-csv.adoc[]

.Syntax

[source,cli]
xcp scan -html <ip_address_or_hostname>:/source_vol

include::./_include/ref-example-nfs-scan-html.adoc[]

== scan -nonames

Use the `-nonames` parameter with the `scan` command to exclude user and group names from file listings or reports.

NOTE: When used with the `scan` command, the `-nonames` parameter only applies to file listings returned using the `-l` option.

.Syntax

[source,cli]
xcp scan -nonames <ip_address_or_hostname>:/source_vol

include::./_include/ref-example-nfs-scan-nonames.adoc[]

[[nfs_scan_newid]]
== scan -newid <name>

Use the `-newid <name>` parameter with the `scan` command to specify the catalog name for a new index when running a scan.

.Syntax

[source,cli]
xcp scan -newid <name> <ip_address_or_hostname>:/source_vol

include::./_include/ref-example-nfs-scan-newid.adoc[]

[[nfs_scan_id]]
== scan -id <catalog_name>

Use the `-id` parameter with the `scan` command to specify the catalog name of previous copy or scan index.

.Syntax

[source,cli]
xcp scan -id <catalog_name> 

include::./_include/ref-example-nfs-scan-id.adoc[]

[[nfs_scan_match]]
== scan -match <filter>

Use the `-match <filter>` parameter with the `scan` command to specify that only the files and directories that match a filter are processed.

.Syntax 

[source,cli]
xcp scan -match <filter> <ip_address_or_hostname>:/source_vol

include::./_include/ref-example-nfs-scan-match.adoc[]

[[nfs_scan_fmt]]
== scan -fmt <string_expression>

Use the `-fmt` parameter with the `scan` command to specify that only files and directories that match the specified format are returned.

.Syntax

[source,cli]
xcp scan -fmt <string_expression> <ip_address_or_hostname>:/source_vol

include::./_include/ref-example-nfs-scan-fmt.adoc[]


[[nfs_scan_du]]
== scan -du

Use the `-du` parameter with the `scan` command to summarize the space usage of each directory, including subdirectories.

.Syntax

[source,cli]
xcp scan -du <ip_address_or_hostname>:/source_vol

include::./_include/ref-example-nfs-scan-du.adoc[]

[[nfs_scan_md5]]
== scan -md5 <string_expression>

Use the `-md5` parameter with the `scan` command to generate checksums for the file listings and save the checksums when indexing. The default value is set to false.

NOTE: The checksums are not used for file verification; they are only used for file listings during scan operations.

.Syntax

[source,cli]
xcp scan -md5 <ip_address_or_hostname>:/source_vol

include::./_include/ref-example-nfs-scan-md5.adoc[]

[[nfs_scan_depth]]
== scan -depth <n>

Use the `-depth <n>` parameter with the `scan` command to limit the search depth of a scan. The `-depth <n>` parameter specifies the depth into the subdirectories that XCP can scan files. For example, if the number 2 is specified, XCP will only scan the first two subdirectory levels.

.Syntax

[source,cli]
xcp scan -depth <n> <ip_address_or_hostname>:/source_vol

include::./_include/ref-example-nfs-scan-depth.adoc[]

[[nfs_scan_dircount]]
== scan -dircount <n[k]>

Use the `-dircount <n[k]>` parameter with the `scan` command to specify the request size when reading directories in a scan. The default value is 64k.

.Syntax

[source,cli]
xcp scan -dircount <n[k]> <ip_address_or_hostname>:/source_vol

include::./_include/ref-example-nfs-scan-dircount.adoc[]

[[nfs_scan_edupe]]
== scan -edupe

Use the `-edupe` parameter with the `scan` command to include the deduplication estimate in reports.

NOTE: Simple Storage Service (S3) does not support sparse files. Therefore, specifying an S3 bucket as the target destination for `scan -edupe` returns the value "None" for sparse data.

.Syntax

[source,cli]
xcp scan -edupe <ip_address_or_hostname>:/source_vol

include::./_include/ref-example-nfs-scan-edupe.adoc[]

[[nfs_scan_bs]]
== scan -bs <n[k]>

Use the `-bs <n[k]>` parameter with the `scan` command to specify the read/write block size. This applies to scans that read data using the `-md5` or `-edupe` parameters. The default block size is 64k. 

.Syntax

[source,cli]
xcp scan -bs <n[k]> <ip_address_or_hostname>:/source_vol

include::./_include/ref-example-nfs-scan-bs.adoc[]

[[nfs_scan_parallel]]
== scan -parallel <n> 

Use the `-parallel` parameter with the `scan` command to specify the maximum number of concurrent batch processes. The default value is 7.

.Syntax

[source,cli]
xcp scan -parallel <n> <ip_address_or_hostname>:/source_vol

include::./_include/ref-example-nfs-scan-parallel.adoc[]

[[nfs_scan_noid]]
== scan -noId

Use the `-noId` parameter with the `scan` command to disable the creation of a default index. The default value is false.

.Syntax

[source,cli]
xcp scan -noId <ip_address_or_hostname>:/source_vol

include::./_include/ref-example-nfs-scan-noid.adoc[]

[[nfs_scan_subdir]]
== scan -subdir-names

Use the `-subdir-names` parameter with the `scan` command to retrieve the names of the top-level subdirectories in a directory. 

.Syntax

[source,cli]
xcp scan -subdir-names <ip_address_or_hostname>:/source_vol

include::./_include/ref-example-nfs-scan-subdir-names.adoc[]


== scan -preserve-atime 

Use the `-preserve-atime` parameter with the `scan` command to restore all files to the last accessed date on the source. 

When an NFS share is scanned, the access time is modified on the files if the storage system is configured to modify access time on read. XCP does not directly change the access time. XCP reads the files one by one and this triggers an update to the access time. The `-preserve-atime` option resets the access time to the original value set before the XCP read operation.

.Syntax

[source,cli]
xcp scan -preserve-atime <ip_address_or_hostname>:/source_vol

include::./_include/ref-example-nfs-scan-preserveatime.adoc[]

== scan -s3.insecure

Use the `-s3.insecure` parameter with the `scan` command to use HTTP instead of HTTPS for S3 bucket communication.

.Syntax

[source,cli]
xcp scan -s3.insecure s3://<bucket_name>

include::./_include/ref-example-nfs-scan-s3-insecure.adoc[]

[[nfs_scan_endpoint]]
== scan -s3.endpoint <s3_endpoint_url>

Use the `-s3.endpoint <s3_endpoint_url>` parameter with the `scan` command to override the default AWS endpoint URL with a specified URL for S3 bucket communication.

.Syntax

[source,cli]
xcp scan -s3.endpoint https://<endpoint_url>: s3://<bucket_name>

include::./_include/ref-example-nfs-scan-s3-endpoint.adoc[]

[[nfs_scan_s3_profile]]
== scan -s3.profile <name>

Use the `s3.profile` parameter with the `scan` command to specify a profile from the AWS credential file for S3 bucket communication.

.Syntax

[source,cli]
xcp scan -s3.profile <name> -s3.endpoint https://<endpoint_url>: s3://<bucket_name>

include::./_include/ref-example-nfs-scan-s3-profile.adoc[]

== scan -s3.noverify

Use the `-s3.noverify` parameter with the `scan` command to override the default verification of SSL certification for S3 bucket communication. 

.Syntax

[source,cli]
xcp scan -s3.noverify s3://<bucket_name>

include::./_include/ref-example-nfs-scan-s3-noverify.adoc[]

