---
sidebar: sidebar
permalink: xcp-nfs-reference-scan.html
keywords: netapp, xcp, reference, nfs, command, commands
summary: XCP NFS command reference
---

= scan
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[lead]
The XCP NFS `scan` command recursively scans the entire source NFSv3 exported paths and returns file structure statistics. 

NetApp recommends that you put the source NFS export mounts in read-only mode during the scan operation.

.Syntax
[source,cli]
xcp scan <source_nfs_export_path>

.Show example
[%collapsible]
====
<enter_example>
====

== Parameters

The following table lists the `scan` parameters and their description.

[cols=2*,options="header"]
|===
| Parameter
| Description
| `scan -l` | Retrieves file listing output formats.
| `scan -q` | Retrieves file listing output formats.
| `scan -stats` | Retrieves tree statistic report formats.
| `scan -csv` | Retrieves tree statistic report formats.
| `scan -html` | Retrieves tree statistic report formats.
| `scan -nonames` | Excludes user and group names for file listings and reports.
| `scan -newid <name>` | Specifies the catalog name for a new index.
| `scan -id <name>` | Specifies the catalog name of a previous copy or scan index.
| `scan -match <filter>` | Only processes files and directories that match the filter.
| `scan -fmt <string_expression>` | Only processes files and directories that match the format.
| `scan -du` | Summarizes the space usage of each directory, including subdirectories.
| `scan -md5 <string_expression>` | Generates checksums on the files and saves the checksums when indexing (default: false). 
| `scan -depth <n>` | Limits the search depth.
| `scan -dircount <n[k]>` | Specifies the request size when reading directories.
| `scan -edupe` | Includes the dedupe estimate in reports.
| `scan -bs <n[k]>` | Specifies the read/write block size for scans that read data using `-md5` or `-edupe` (default: 64k).
| `scan -parallel <n>` | Specifies the maximum number of concurrent batch processes (default: 7). 
| `scan -noId` | Disables the creation of a default index (default: false).
| `scan -subdir-names` | Retrieves the names of the top-level subdirectories in a directory.
| `scan -acl4` | Processes NFSv4 access control lists (ACLs).
| `scan -preserve-atime` | Restores all files to the last accessed date on the source.
| `scan -s3.insecure` | Provides the option to use HTTP instead of HTTPS for S3 bucket communication.
| `scan -s3.endpoint <s3_endpoint_url>` | Overrides the default Amazon Web Services (AWS) endpoint URL with the specified URL for S3 bucket communication.
| `scan -s3.profile <profile_name>` | Specifies a profile from the AWS credential file for S3 bucket communication.
| `scan -s3.noverify` | Overrides the default verification of SSL certification for S3 bucket communication.

|===

== Use scan command parameters

This section provides the parameters, descriptions, and examples for the XCP NFS `scan` command

=== Retrieve file listing output formats

You can retrieve file listing output formats by using the following parameters: 

* `scan -l`
* `scan -q`

.Syntax

[source,cli]
xcp scan -l <ip_address_or_hostname>:/<source_vol>

.Show example
[%collapsible]
====
<enter_example>
====

.Syntax

[source,cli]
xcp scan -q <ip_address_or_hostname>:/<source_vol>

.Show example
[%collapsible]
====
<enter_example>
====

=== Retrieve tree statistic report formats

You can retrieve tree statistic report formats by using the following parameters:

* `scan -stats`
* `scan -csv` 
* `scan -html` 

NOTE: XCP reports (.csv, .html) are saved in the catalog location specified in the `xcp.ini` file. The files are stored in the `<catalog path>/catalog/indexes/1/reports` folder. You can view sample reports in the appendix.

.Syntax

[source,cli]
xcp scan -stats <ip_address>:/<source_vol>

.Show example
[%collapsible]
====
<enter_example>
====

.Syntax

[source,cli]
xcp scan -csv <ip_address_or_hostname>:/<source_vol>

.Show example
[%collapsible]
====
<enter_example>
====

.Syntax

[source,cli]
xcp scan -html <ip_address_or_hostname>:/<source_vol>

.Show example
[%collapsible]
====
<enter_example>
====

=== Exclude user and group names for file listings or reports

You can exclude user and group names for file listings or reports by using the `-nonames` parameter.

NOTE: When used with the `scan` command, the `-nonames` parameter only applies to file listings returned using the `-l` option.

.Syntax

[source,cli]
xcp scan -nonames <ip_address_or_hostname>:/<source_vol>

.Show example
[%collapsible]
====
<enter_example>
====

=== Specify the catalog name for a new index

You can specify the catalog name for a new index when running a scan by using the `-newid <name>` parameter. 

.Syntax

[source,cli]
xcp scan -newid <name> <ip_address_or_hostname>:/<source_vol>

.Show example
[%collapsible]
====
<enter_example>
====

=== Specify the catalog name of a previous copy or scan index

You can specify the catalog name of previous copy or scan index by using the `-id <name>` parameter.

.Syntax

[source,cli]
xcp scan -id <name> 

.Show example
[%collapsible]
====
<enter_example>
====


=== Only process the files and directories that match the filter

You can specify that only the files and directories that match a filter are processed by using the `-match <filter>` parameter.

.Syntax 

[source,cli]
xcp scan -match <filter> <ip_address_or_hostname>:/<source_vol>

.Show example
[%collapsible]
====
<enter_example>
====

=== Only process the files and directories that match the format

You can specify that only files and directories that match the specified format are returned by using the `-fmt` parameter.

.Syntax

[source,cli]
xcp scan -fmt <string_expression> <ip_address_or_hostname>:/<source_vol>

.Show example
[%collapsible]
====
<enter_example>
====

=== Summarize the space usage of each directory, including subdirectories

You can summarize the space usage of each directory, including subdirectories, by using the `-du` parameter.

.Syntax

[source,cli]
xcp scan -du <ip_address_or_hostname>:/<source_vol>

.Show example
[%collapsible]
====
<enter_example>
====

=== Generate checksums for file listings and save the checksums when indexing

You can generate checksums for the file listings and save the checksums when indexing by using the `-md5` parameter. The default value is set to false.

NOTE: The checksums are not used for file verification; they are only used for file listings during scan operations.

.Syntax

[source,cli]
xcp scan -md5 <ip_address_or_hostname>:/<source_vol>

.Show example
[%collapsible]
====
<enter_example>
====

=== Limit the search depth

You can limit the search depth of a scan by using the `- depth <n>` parameter. The `-depth <n>` parameter specifies the depth into the subdirectories that XCP can scan files. For example, if the number 2 is specified, XCP will only scan the first two subdirectory levels.

.Syntax

[source,cli]
xcp scan -depth <number> <ip_address_or_hostname>:/<source_vol>

.Show example
[%collapsible]
====
<enter_example>
====

=== Specify the request size when reading directories

You can specify the request size when reading directories in a scan by using the `-dircount <number>` parameter. The default value is 64k.

.Syntax

[source,cli]
xcp scan -dircount 64k <ip_address_or_hostname>:/<source_vol>

.Show example
[%collapsible]
====
<enter_example>
====

=== Include the dedupe estimate in reports

You can include the dedupe estimate in reports by using the `-edupe` parameter.

.Syntax

[source,cli]
xcp scan -edupe <ip_address_or_hostname>:/<source_vol>

.Show example
[%collapsible]
====
<enter_example>
====

=== Specify the read/write block size for scans that read data using `-md5` or `-edupe`

You can specify the read/write block size for scans that read data using the `-md5` or `-edupe` parameters by specifying the `-bs <number>` parameter. The default block size is 64k. 

.Syntax

[source,cli]
xcp scan -bs <number> <ip_address_or_hostname>:/<source_vol>

.Show example
[%collapsible]
====
<enter_example>
====

=== Specify  the maximum number of concurrent batch processes 

You can specify the maximum number of concurrent patch processes by using the `- parallel <number>` parameter. The default value is 7.

.Syntax

[source,cli]
xcp scan -parallel <number> <ip_address_or_hostname>:/<source_vol>

.Show example
[%collapsible]
====
<enter_example>
====

=== Disable the creation of a default index

You can disable the creation of a default index by using the `-noId` parameter. The default value is false.

.Syntax

[source,cli]
xcp scan -noId <ip_address_or_hostname>:/<source_vol>

.Show example
[%collapsible]
====
<enter_example>
====

=== Retrieve the names of the top-level subdirectories in a directory

You can retrieve the names of the top-level subdirectories in a directory by using the `-subdir-names` parameter. 

.Syntax

[source,cli]
xcp scan -subdir-names <ip_address_or_hostname>:/<source_vol>

.Show example
[%collapsible]
====
<enter_example>
====

=== Process NFSv4 access control lists (ACLs)

You can process NFSv4 ACLs by using the `-acl4` parameter. 

.Syntax

[source,cli]
xcp scan -acl4 <ip_address_or_hostname>:/<source_vol>

.Show example
[%collapsible]
====
<enter_example>
====

=== Restore all files to the last accessed date on the source

You can restore all files to the last accessed date on the source by using the `-preserve-atime` parameter. 

When an NFS share is scanned, the access time is modified on the files if the storage system is configured to modify access time on read. XCP does not directly change the access time, XCP reads the files one by one and this triggers an update to the access time. The `-preserve-atime` option resets the access time to the original value set before the XCP read operation.

.Syntax

[source,cli]
xcp scan -preserve-atime <ip_address_or_hostname>:/<source_vol>

.Show example
[%collapsible]
====
<enter_example>
====

=== Use HTTP instead of HTTPS for S3 bucket communication

You can use HTTP instead of HTTPS for S3 bucket communication by using the `-s3.insecure` parameter. 

.Syntax

[source,cli]
xcp scan -s3.insecure s3://<bucket_name>

.Show example
[%collapsible]
====
<enter_example>
====

=== Override the default Amazon Web Services (AWS) endpoint URL with the specified URL for S3 bucket communication

You can override the default AWS endpoint URL with the specified URL for S3 bucket communication by using the `-s3.endpoint <s3_endpoint_url>` parameter. 

.Syntax

[source,cli]
xcp scan -s3.endpoint https://<endpoint_url>: s3://<bucket_name>

.Show example
[%collapsible]
====
<enter_example>
====

=== Specify a profile from the AWS credential file for S3 bucket communication

You can specify a profile from the AWS credential file for S3 bucket communication by using the `-s3.profile <profile_name>` parameter. 

.Syntax

[source,cli]
xcp scan -s3.profile <name> -s3.endpoint https://<endpoint_url>: s3://<bucket_name>

.Show example
[%collapsible]
====
<enter_example>
====

=== Override the default verification of SSL certification for S3 bucket communication 

You can override the default verification of SSL certification for S3 bucket communication by using the `-s3.noverify` parameter. 

.Syntax

[source,cli]
xcp scan -s3.noverify s3://<bucket_name>

.Show example
[%collapsible]
====
<enter_example>
====

