---
sidebar: sidebar
permalink: xcp-environment-variable.html
keywords: netapp, xcp, configure, configuring, how, performing, tuning, nfs, enviroment,
summary: Environment variable (NFS only)
---

= Environment variable (NFS only)
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Optional environment variable configuration for NFS systems.

The environment variable XCP_CONFIG_DIR overrides the default location, `/opt/NetApp/xFiles/xcp`. If set, the value should be an OS filesystem path, possibly to a mounted NFS directory. When a custom configuration directory is set, the log file is named `xcp.hostname.log` instead of the default, `xcp.log`.

----
[root@localhost /]# export XCP_CONFIG_DIR ='/tmp/xcp_config_dir_path'
----

The environment variable XCP_LOG_DIR overrides the default location that stores the XCP log in the configuration directory. If set, the value should be an OS filesystem path, possibly to a mounted NFS directory. When a custom log directory is set, the log file is named `xcp.hostname.log` instead of the default, `xcp.log`.

----
[root@localhost /]# export XCP_LOG_DIR='/tmp/xcp_log_dir_path'
----

The environment variable XCP_CATALOG_PATH overrides the setting in xcp.ini. If set, the value should be in the xcp path format, `server:export[:subdirectory]`.

----
[root@localhost /]# export XCP_CATALOG_PATH='10.61.82.210:/vol/xcpvol/'
----
