---
sidebar: sidebar
permalink: xcp-install-xcp-smb.html
keywords: netapp, xcp, install, smb
summary: Installing XCP SMB
---

= Install XCP SMB
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

This section details the system requirements and the procedure for VC++ redistributable installation and the initial setup of XCP on a Windows client.

NOTE:	There is no option to upgrade; reinstall XCP to replace any existing version.

*System Requirements*

[cols="35,65"]
|===
|Item |Requirement

|System
|64-bit Intel or AMD server, minimum 4 cores and 32 GB RAM
|Operating System & Software
|Windows 2012 R2 or above. For supported Microsoft OS versions, see the link:https://mysupport.netapp.com/matrix/#welcome[Interoperability Matrix Tool^].

Visual C++ 2017 redistributable must be installed on the XCP host.

|Special Requirements
|The source storage system, XCP host, and the target ONTAP system must be part of same Active Directory domain
|Storage
|20 MB of disk space for the XCP binary and at least 50 MB of disk space for the logs that are stored in the C:\NetApp\XCP directory
|Supported Protocol Version
|All SMB protocol versions
|Supported browser (File Analytics only)
|XCP File Analytics supports Google Chrome version 76 and later. See the IMT matrix for all the supported versions of the browser
|===

=== XCP SMB Microsoft VC++ Redistributable installation

Follow these steps for the VC++ redistributable installation.

.Steps

. Click link:https://go.microsoft.com/fwlink/?LinkId=746572[VC++ 2017 redistributable^] to download the executable to your default downloads folder.
+
. To start the installation, double click the installer. Accept the terms and conditions and select *Install*.
+
.	When the installation is complete, restart the Windows client.

=== XCP SMB Initial Setup Procedure

Follow these steps to perform the initial setup of XCP SMB.

.Steps

. Download the license and the XCP SMB binary `NETAPP_XCP_<version>.tgz` on a Windows client.
. Untar the `NETAPP_XCP_<version>.tgz` file.
. Copy the `xcp.exe` file to your Windows C: drive, this binary is available inside `/xcp/windows` after you untar the `tgz` file.
. Verify that the `C:\NetApp\XCP` path is available on the system from a previous version of XCP.
If `C:\NetApp\XCP` is available, activate XCP by using the `xcp activate` command and proceed with data migration.
+
If `C:\NetApp\XCP` is not available, the system creates the XCP host configuration directory and files at `C:\NetApp\XCP` when you run the `xcp activate` command for the first time. The `activate xcp` command fails and creates an error message asking for a new license.
+
----
C:\>xcp.exe activate
(c) yyyy NetApp, Inc.

License file C:\NetApp\XCP\license not found.
Register for a license at https://xcp.netapp.com
----
+
. Copy the license to the newly created folder `C:\NetApp\XCP:`
+
----
C:\>copy license c:\NetApp\XCP
        1 file(s) copied.
----
+
.	Activate XCP:
+
----
C:\>xcp.exe activate
XCP SMB; (c) 2020 NetApp, Inc.;

XCP already activated

C:\>
----

// 2021-12-10, BURT 1442440
