---
sidebar: sidebar
permalink: xcp-nfs-reference-sync.html
keywords: netapp, xcp, reference, nfs, command, commands
summary: XCP NFS command reference
---

= sync 
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[lead]
The XCP NFS `sync` command scans for changes and modifications a source NFS directory using a catalog index tag name or the number of a previous copy operation. Incremental changes to the source are copied and applied to the target directory. The old catalog index numbers are replaced with new ones after the sync operation.

NOTE: During the sync operation, modified files and directories are copied to the destination NFSv3 export again.

.Syntax
[source,cli]
xcp sync -id <catalog_name>

[[sync_id]]
.Show example
[%collapsible]
====
<enter_example>
====

The following table lists the `sync` parameters and their description.

[cols=2*,options="header"]
|===
| Parameter
| Description
| <<sync_id, sync -id <catalog_index> >> | Specifies the catalog name of a previous copy index.
| <<sync_nonames, sync -nonames>> | Excludes user and group names for file listings and reports.
| <<sync_bs, sync -bs <n[k]> >> | Specifies the read/write block size (default: 64k).
| <<sync_dircount, sync -dircount <n[k]> >> | Specifies the request size when reading directories.
| <<sync_parallel, sync -parallel <n> >> | Specifies the maximum number of concurrent batch processes (default: 7). 
| <<sync_preserve_atime, sync -preserve-atime>> | Restores all files to the last accessed date on the source.

|===


[[sync_nonames]]
== sync -id and sync -nonames

Use the the `-id <catalog_name> and `-nonames` parameters with the `sync` command to exclude user and group names for file listings or reports.

.Syntax

[source,cli]
xcp sync -id <catalog_name> -nonames 

.Show example
[%collapsible]
====
<enter_example>
====

[[sync_bs]]
== sync -id <catalog_name> and sync -bs <n[k]>

Use the the `-id <catalog_name> and `-bs <n[k]>` parameters with the `sync` command to  specify the read/write block size. The default block size is 64k. 

.Syntax

[source,cli]
xcp sync -id <catalog_name> -bs <n[k]>

.Show example
[%collapsible]
====
<enter_example>
====

[[sync_dircount]]
== sync -id and sync -dircount <n[k]>

Use the the `-id <catalog_name> and `-dircount <n[k]>` parameters with the `sync` command to specify the request size when reading directories. The default value is 64k.

.Syntax

[source,cli]
xcp sync -id <catalog_name> -dircount <n[k]>

.Show example
[%collapsible]
====
<enter_example>
====

[[sync_parallel]]
== sync -id and sync -parallel 

Use the the `-id <catalog_name> and `-parallel` parameters with the `sync` command to specify the maximum number of concurrent batch processes. The default value is 7.

.Syntax

[source,cli]
xcp sync -id <catalog_name> -parallel <n> 

.Show example
[%collapsible]
====
<enter_example>
====

[[sync_preserve_atime]]
== sync -preserve-atime

Use the the `-preserve-atime` parameter with the `sync` command to restore all files to the last accessed date on the source. 

The `-preserve-atime` option resets the access time to the original value set before the XCP read operation.

.Syntax

[source,cli]
xcp sync -preserve-atime -id <catalog_name>

.Show example
[%collapsible]
====
<enter_example>
====
