---
sidebar: sidebar
permalink: xcp-install-file-analytics-for-nfs.html
keywords: netapp, xcp, install, installing, file, analytics, nfs, upgrade, upgrading
summary: Install or upgrade File Analytics for NFS
---

= Install File Analytics for NFS
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Install or upgrade File Analytics for NFS.

.About this task
For system requirements for NFS, see link:xcp-install-xcp-nfs.html[Install XCP NFS].

The `configure.sh` script installs and enables default configurations of HTTPD and PostgreSQL available for Linux server. You can change or update to a more recent version as needed and to adhere to security guidelines. To learn more about the `configure.sh` script, run `./configure.sh -h`

.Before you begin

* You cannot run the XCP application and XCP as service simultaneously on the same host.
+
If any XCP operations are running, complete the operations before you start configuration.
* Your Linux machine must be connected to the Yum repository server or the internet.
* If a firewall is configured on the Linux machine, you must change the firewall settings to enable the ports used by XCP, the XCP service, and the services used by XCP File Analytics. For more information, go to xref:xcp-ports-used.html[Ports used by XCP].

.Steps

. Install or upgrade File Analytics for NFS.
+
[role="tabbed-block"]
====
.Install File Analytics
--
.. Navigate to the `xcp` folder and run the `./configure.sh` script.
+
+
... Download PostgreSQL packages
... Install the PostgreSQL server
... Install the HTTPD server
... Use OpenSSL to create a self-signed certificate (`server.key and server.crt`)
... Create the XCP File Analytics database
--
.Upgrade File Analytics
--
.. Navigate to the `xcp` folder and run `./configure.sh -f`.
+
----
[root@user-1 xcp]# ./configure.sh -f
Cleanup and re-configure the system.
 Do you wish to continue(y/n):y
----
+
Once approved, the script cleans up the existing configuration and reconfigures the system. 
--
====

. Verify the XCP service.
+
Use the following command to verify the XCP service is running:
+
`service xcp status`
. Launch File Analytics in a supported browser: *\https://<ip address of linux>/xcp*.
+
Refer to link:xcp-install-xcp-nfs.html[Install XCP NFS] for information on supported browsers.

// 23 Oct 2023, OTHERDOC-34
// BURT 1391465 06/29/2021
